#ifndef ROMAN_DICT_H
#define ROMAN_DICT_H

#include <windows.h>
#include <tchar.h>

struct RomanPattern {
    const TCHAR* pattern;
    const TCHAR* typePatterns[100];
};

const RomanPattern g_RomanDict[] = {
    { _T("あ"), { _T("a"), NULL } },
    { _T("い"), { _T("i"), _T("yi"), NULL } },
    { _T("う"), { _T("u"), _T("wu"), _T("whu"), NULL } },
    { _T("え"), { _T("e"), NULL } },
    { _T("お"), { _T("o"), NULL } },
    { _T("か"), { _T("ka"), _T("ca"), NULL } },
    { _T("き"), { _T("ki"), NULL } },
    { _T("く"), { _T("ku"), _T("cu"), _T("qu"), NULL } },
    { _T("け"), { _T("ke"), NULL } },
    { _T("こ"), { _T("ko"), _T("co"), NULL } },
    { _T("さ"), { _T("sa"), NULL } },
    { _T("し"), { _T("si"), _T("shi"), _T("ci"), NULL } },
    { _T("す"), { _T("su"), NULL } },
    { _T("せ"), { _T("se"), _T("ce"), NULL } },
    { _T("そ"), { _T("so"), NULL } },
    { _T("た"), { _T("ta"), NULL } },
    { _T("ち"), { _T("ti"), _T("chi"), NULL } },
    { _T("つ"), { _T("tu"), _T("tsu"), NULL } },
    { _T("て"), { _T("te"), NULL } },
    { _T("と"), { _T("to"), NULL } },
    { _T("な"), { _T("na"), NULL } },
    { _T("に"), { _T("ni"), NULL } },
    { _T("ぬ"), { _T("nu"), NULL } },
    { _T("ね"), { _T("ne"), NULL } },
    { _T("の"), { _T("no"), NULL } },
    { _T("は"), { _T("ha"), NULL } },
    { _T("ひ"), { _T("hi"), NULL } },
    { _T("ふ"), { _T("fu"), _T("hu"), NULL } },
    { _T("へ"), { _T("he"), NULL } },
    { _T("ほ"), { _T("ho"), NULL } },
    { _T("ま"), { _T("ma"), NULL } },
    { _T("み"), { _T("mi"), NULL } },
    { _T("む"), { _T("mu"), NULL } },
    { _T("め"), { _T("me"), NULL } },
    { _T("も"), { _T("mo"), NULL } },
    { _T("や"), { _T("ya"), NULL } },
    { _T("ゆ"), { _T("yu"), NULL } },
    { _T("よ"), { _T("yo"), NULL } },
    { _T("ら"), { _T("ra"), NULL } },
    { _T("り"), { _T("ri"), NULL } },
    { _T("る"), { _T("ru"), NULL } },
    { _T("れ"), { _T("re"), NULL } },
    { _T("ろ"), { _T("ro"), NULL } },
    { _T("わ"), { _T("wa"), NULL } },
    { _T("を"), { _T("wo"), NULL } },
    { _T("ん"), { _T("nn"), _T("xn"), NULL } },
    { _T("が"), { _T("ga"), NULL } },
    { _T("ぎ"), { _T("gi"), NULL } },
    { _T("ぐ"), { _T("gu"), NULL } },
    { _T("げ"), { _T("ge"), NULL } },
    { _T("ご"), { _T("go"), NULL } },
    { _T("ざ"), { _T("za"), NULL } },
    { _T("じ"), { _T("ji"), _T("zi"), NULL } },
    { _T("ず"), { _T("zu"), NULL } },
    { _T("ぜ"), { _T("ze"), NULL } },
    { _T("ぞ"), { _T("zo"), NULL } },
    { _T("だ"), { _T("da"), NULL } },
    { _T("ぢ"), { _T("di"), NULL } },
    { _T("づ"), { _T("du"), NULL } },
    { _T("で"), { _T("de"), NULL } },
    { _T("ど"), { _T("do"), NULL } },
    { _T("ば"), { _T("ba"), NULL } },
    { _T("び"), { _T("bi"), NULL } },
    { _T("ぶ"), { _T("bu"), NULL } },
    { _T("べ"), { _T("be"), NULL } },
    { _T("ぼ"), { _T("bo"), NULL } },
    { _T("ぱ"), { _T("pa"), NULL } },
    { _T("ぴ"), { _T("pi"), NULL } },
    { _T("ぷ"), { _T("pu"), NULL } },
    { _T("ぺ"), { _T("pe"), NULL } },
    { _T("ぽ"), { _T("po"), NULL } },
    { _T("ぁ"), { _T("la"), _T("xa"), NULL } },
    { _T("ぃ"), { _T("li"), _T("xi"), _T("lyi"), _T("xyi"), NULL } },
    { _T("ぅ"), { _T("lu"), _T("xu"), NULL } },
    { _T("ぇ"), { _T("le"), _T("xe"), _T("lye"), _T("xye"), NULL } },
    { _T("ぉ"), { _T("lo"), _T("xo"), NULL } },
    { _T("ゃ"), { _T("lya"), _T("xya"), NULL } },
    { _T("ゅ"), { _T("lyu"), _T("xyu"), NULL } },
    { _T("ょ"), { _T("lyo"), _T("xyo"), NULL } },
    { _T("っ"), { _T("ltu"), _T("ltsu"), _T("xtu"), _T("xtsu"), NULL } },
    { _T("きゃ"), { _T("kya"), _T("kilya"), _T("kixya"), NULL } },
    { _T("きぃ"), { _T("kyi"), _T("kili"), _T("kilyi"), _T("kixi"), _T("kixyi"), NULL } },
    { _T("きゅ"), { _T("kyu"), _T("kilyu"), _T("kixyu"), NULL } },
    { _T("きぇ"), { _T("kye"), _T("kile"), _T("kilye"), _T("kixe"), _T("kixye"), NULL } },
    { _T("きょ"), { _T("kyo"), _T("kilyo"), _T("kixyo"), NULL } },
    { _T("ぎゃ"), { _T("gya"), _T("gilya"), _T("gixya"), NULL } },
    { _T("ぎぃ"), { _T("gyi"), _T("gili"), _T("gilyi"), _T("gixi"), _T("gixyi"), NULL } },
    { _T("ぎゅ"), { _T("gyu"), _T("gilyu"), _T("gixyu"), NULL } },
    { _T("ぎぇ"), { _T("gye"), _T("gile"), _T("gilye"), _T("gixe"), _T("gixye"), NULL } },
    { _T("ぎょ"), { _T("gyo"), _T("gilyo"), _T("gixyo"), NULL } },
    { _T("くぁ"), { _T("qa"), _T("kwa"), _T("kula"), _T("kuxa"), _T("cula"), _T("cuxa"), _T("qula"), _T("quxa"), NULL } },
    { _T("くぃ"), { _T("qi"), _T("qyi"), _T("kuli"), _T("kuxi"), _T("kulyi"), _T("kuxyi"), _T("culi"), _T("culyi"), _T("cuxi"), _T("cuxyi"), _T("quli"), _T("quxi"), _T("qulyi"), _T("quxyi"), NULL } },
    { _T("くぅ"), { _T("qwu"), _T("kulu"), _T("kuxu"), _T("culu"), _T("cuxu"), _T("qulu"), _T("quxu"), NULL } },
    { _T("くぇ"), { _T("qe"), _T("qwe"), _T("kule"), _T("kuxe"), _T("kulye"), _T("kuxye"), _T("cule"), _T("cuxe"), _T("culye"), _T("cuxye"), _T("qule"), _T("quxe"), _T("qulye"), _T("quxye"), NULL } },
    { _T("くぉ"), { _T("qo"), _T("qwo"), _T("kulo"), _T("kuxo"), _T("culo"), _T("cuxo"), _T("qulo"), _T("quxo"), NULL } },
    { _T("ぐぁ"), { _T("gwa"), _T("gula"), _T("guxa"), NULL } },
    { _T("ぐぃ"), { _T("gwi"), _T("guli"), _T("gulyi"), _T("guxi"), _T("guxyi"), NULL } },
    { _T("ぐぅ"), { _T("gwu"), _T("gulu"), _T("guxu"), NULL } },
    { _T("ぐぇ"), { _T("gwe"), _T("gule"), _T("guxe"), _T("gulye"), _T("guxye"), NULL } },
    { _T("ぐぉ"), { _T("gwo"), _T("gulo"), _T("guxo"), NULL } },
    { _T("しゃ"), { _T("sya"), _T("sha"), _T("silya"), _T("sixya"), _T("shilya"), _T("shixya"), _T("cilya"), _T("cixya"), NULL } },
    { _T("しぃ"), { _T("syi"), _T("sili"), _T("sixi"), _T("silyi"), _T("sixyi"), _T("shili"), _T("shixi"), _T("shilyi"), _T("shixyi"), _T("cili"), _T("cixi"), _T("cilyi"), _T("cixyi"), NULL } },
    { _T("しゅ"), { _T("syu"), _T("shu"), _T("silyu"), _T("sixyu"), _T("shilyu"), _T("shixyu"), _T("cilyu"), _T("cixyu"), NULL } },
    { _T("しぇ"), { _T("sye"), _T("she"), _T("sile"), _T("silye"), _T("sixe"), _T("sixye"), _T("shile"), _T("shilye"), _T("shixe"), _T("shixye"), _T("cile"), _T("cilye"), _T("cixe"), _T("cixye"), NULL } },
    { _T("しょ"), { _T("syo"), _T("sho"), _T("silyo"), _T("sixyo"), _T("shilyo"), _T("shixyo"), _T("cilyo"), _T("cixyo"), NULL } },
    { _T("じゃ"), { _T("ja"), _T("jya"), _T("zya"), _T("jilya"), _T("jixya"), _T("zilya"), _T("zixya"), NULL } },
    { _T("じぃ"), { _T("jyi"), _T("zyi"), _T("jili"), _T("jixi"), _T("jilyi"), _T("jixyi"), _T("zili"), _T("zixi"), _T("zilyi"), _T("zixyi"), NULL } },
    { _T("じゅ"), { _T("ju"), _T("jyu"), _T("zyu"), _T("jilyu"), _T("jixyu"), _T("zilyu"), _T("zixyu"), NULL } },
    { _T("じぇ"), { _T("je"), _T("jye"), _T("zye"), _T("jile"), _T("jixe"), _T("jilye"), _T("jixye"), _T("zile"), _T("zixe"), _T("zilye"), _T("zixye"), NULL } },
    { _T("じょ"), { _T("jo"), _T("jyo"), _T("zyo"), _T("jilyo"), _T("jixyo"), _T("zilyo"), _T("zixyo"), NULL } },
    { _T("すぁ"), { _T("swa"), _T("sula"), _T("suxa"), NULL } },
    { _T("すぃ"), { _T("swi"), _T("suli"), _T("sulyi"), _T("suxi"), _T("suxyi"), NULL } },
    { _T("すぅ"), { _T("swu"), _T("sulu"), _T("suxu"), NULL } },
    { _T("すぇ"), { _T("swe"), _T("sule"), _T("suxe"), _T("sulye"), _T("suxye"), NULL } },
    { _T("すぉ"), { _T("swo"), _T("sulo"), _T("suxo"), NULL } },
    { _T("ちゃ"), { _T("tya"), _T("cha"), _T("cya"), _T("tilya"), _T("tixya"), _T("chilya"), _T("chixya"), NULL } },
    { _T("ちぃ"), { _T("tyi"), _T("cyi"), _T("tili"), _T("tixi"), _T("tilyi"), _T("tixyi"), _T("chili"), _T("chixi"), _T("chilyi"), _T("chixyi"), NULL } },
    { _T("ちゅ"), { _T("tyu"), _T("chu"), _T("cyu"), _T("tilyu"), _T("tixyu"), _T("chilyu"), _T("chixyu"), NULL } },
    { _T("ちぇ"), { _T("tye"), _T("che"), _T("cye"), _T("tile"), _T("tixe"), _T("tilye"), _T("tixye"), _T("chile"), _T("chixe"), _T("chilye"), _T("chixye"), NULL } },
    { _T("ちょ"), { _T("tyo"), _T("cho"), _T("cyo"), _T("tilyo"), _T("tixyo"), _T("chilyo"), _T("chixyo"), NULL } },
    { _T("ぢゃ"), { _T("dya"), _T("dilya"), _T("dixya"), NULL } },
    { _T("ぢぃ"), { _T("dyi"), _T("dilyi"), _T("dixyi"), NULL } },
    { _T("ぢゅ"), { _T("dyu"), _T("dilyu"), _T("dixyu"), NULL } },
    { _T("ぢぇ"), { _T("dye"), _T("dile"), _T("dixe"), _T("dilye"), _T("dixye"), NULL } },
    { _T("ぢょ"), { _T("dyo"), _T("dilyo"), _T("dixyo"), NULL } },
    { _T("つぁ"), { _T("tsa"), _T("tula"), _T("tuxa"), _T("tsula"), _T("tsuxa"), NULL } },
    { _T("つぃ"), { _T("tsi"), _T("tuli"), _T("tuxi"), _T("tulyi"), _T("tuxyi"), _T("tsuli"), _T("tsuxi"), _T("tsulyi"), _T("tsuxyi"), NULL } },
    { _T("つぇ"), { _T("tse"), _T("tule"), _T("tuxe"), _T("tulye"), _T("tuxye"), _T("tsule"), _T("tsuxe"), _T("tsulye"), _T("tsuxye"), NULL } },
    { _T("つぉ"), { _T("tso"), _T("tulo"), _T("tuxo"), _T("tsulo"), _T("tsuxo"), NULL } },
    { _T("てゃ"), { _T("tha"), _T("telya"), _T("texya"), NULL } },
    { _T("てぃ"), { _T("thi"), _T("teli"), _T("texi"), _T("telyi"), _T("texyi"), NULL } },
    { _T("てゅ"), { _T("thu"), _T("telyu"), _T("texyu"), NULL } },
    { _T("てぇ"), { _T("the"), _T("tele"), _T("texe"), _T("telye"), _T("texye"), NULL } },
    { _T("てょ"), { _T("tho"), _T("telyo"), _T("texyo"), NULL } },
    { _T("でゃ"), { _T("dha"), _T("delya"), _T("dexya"), NULL } },
    { _T("でぃ"), { _T("dhi"), _T("deli"), _T("dexi"), _T("delyi"), _T("dexyi"), NULL } },
    { _T("でゅ"), { _T("dhu"), _T("delyu"), _T("dexyu"), NULL } },
    { _T("でぇ"), { _T("dhe"), _T("dele"), _T("dexe"), _T("delye"), _T("dexye"), NULL } },
    { _T("でょ"), { _T("dho"), _T("delyo"), _T("dexyo"), NULL } },
    { _T("とぁ"), { _T("twa"), _T("tola"), _T("toxa"), NULL } },
    { _T("とぃ"), { _T("twi"), _T("toli"), _T("toxi"), _T("tolyi"), _T("toxyi"), NULL } },
    { _T("とぅ"), { _T("twu"), _T("tolu"), _T("toxu"), NULL } },
    { _T("とぇ"), { _T("twe"), _T("tole"), _T("toxe"), _T("tolye"), _T("toxye"), NULL } },
    { _T("とぉ"), { _T("two"), _T("tolo"), _T("toxo"), NULL } },
    { _T("どぁ"), { _T("dwa"), _T("dola"), _T("doxa"), NULL } },
    { _T("どぃ"), { _T("dwi"), _T("doli"), _T("doxi"), _T("dolyi"), _T("doxyi"), NULL } },
    { _T("どぅ"), { _T("dwu"), _T("dolu"), _T("doxu"), NULL } },
    { _T("どぇ"), { _T("dwe"), _T("dole"), _T("doxe"), _T("dolye"), _T("doxye"), NULL } },
    { _T("どぉ"), { _T("dwo"), _T("dolo"), _T("doxo"), NULL } },
    { _T("にゃ"), { _T("nya"), _T("nilya"), _T("nixya"), NULL } },
    { _T("にぃ"), { _T("nyi"), _T("nili"), _T("nixi"), _T("nilyi"), _T("nixyi"), NULL } },
    { _T("にゅ"), { _T("nyu"), _T("nilyu"), _T("nixyu"), NULL } },
    { _T("にぇ"), { _T("nye"), _T("nile"), _T("nixe"), _T("nilye"), _T("nixye"), NULL } },
    { _T("にょ"), { _T("nyo"), _T("nilyo"), _T("nixyo"), NULL } },
    { _T("ぴゃ"), { _T("pya"), _T("pilya"), _T("pixya"), NULL } },
    { _T("ぴぃ"), { _T("pyi"), _T("pili"), _T("pixi"), _T("pilyi"), _T("pixyi"), NULL } },
    { _T("ぴゅ"), { _T("pyu"), _T("pilyu"), _T("pixyu"), NULL } },
    { _T("ぴぇ"), { _T("pye"), _T("pile"), _T("pixe"), _T("pilye"), _T("pixye"), NULL } },
    { _T("ぴょ"), { _T("pyo"), _T("pilyo"), _T("pixyo"), NULL } },
    { _T("ひゃ"), { _T("hya"), _T("hilya"), _T("hixya"), NULL } },
    { _T("ひぃ"), { _T("hyi"), _T("hili"), _T("hixi"), _T("hilyi"), _T("hixyi"), NULL } },
    { _T("ひゅ"), { _T("hyu"), _T("hilyu"), _T("hixyu"), NULL } },
    { _T("ひぇ"), { _T("hye"), _T("hile"), _T("hixe"), _T("hilye"), _T("hixye"), NULL } },
    { _T("ひょ"), { _T("hyo"), _T("hilyo"), _T("hixyo"), NULL } },
    { _T("びゃ"), { _T("bya"), _T("bilya"), _T("bixya"), NULL } },
    { _T("びぃ"), { _T("byi"), _T("bili"), _T("bixi"), _T("bilyi"), _T("bixyi"), NULL } },
    { _T("びゅ"), { _T("byu"), _T("bilyu"), _T("bixyu"), NULL } },
    { _T("びぇ"), { _T("bye"), _T("bile"), _T("bixe"), _T("bilye"), _T("bixye"), NULL } },
    { _T("びょ"), { _T("byo"), _T("bilyo"), _T("bixyo"), NULL } },
    { _T("ふゃ"), { _T("fya"), _T("fulya"), _T("fuxya"), _T("hulya"), _T("huxya"), NULL } },
    { _T("ふぃ"), { _T("fi"), _T("fyi"), _T("fuli"), _T("fuxi"), _T("fulyi"), _T("fuxyi"), _T("huli"), _T("huxi"), _T("hulyi"), _T("huxyi"), NULL } },
    { _T("ふゅ"), { _T("fyu"), _T("fulyu"), _T("fuxyu"), _T("hulyu"), _T("huxyu"), NULL } },
    { _T("ふぇ"), { _T("fe"), _T("fye"), _T("fule"), _T("fuxe"), _T("fulye"), _T("fuxye"), _T("hule"), _T("huxe"), _T("hulye"), _T("huxye"), NULL } },
    { _T("ふょ"), { _T("fyo"), _T("fulyo"), _T("fuxyo"), _T("hulyo"), _T("huxyo"), NULL } },
    { _T("ふぁ"), { _T("fa"), _T("fula"), _T("fuxa"), _T("hula"), _T("huxa"), NULL } },
    { _T("ふぉ"), { _T("fo"), _T("fulo"), _T("fuxo"), _T("hulo"), _T("huxo"), NULL } },
    { _T("みゃ"), { _T("mya"), _T("milya"), _T("mixya"), NULL } },
    { _T("みぃ"), { _T("myi"), _T("mili"), _T("mixi"), _T("milyi"), _T("mixyi"), NULL } },
    { _T("みゅ"), { _T("myu"), _T("milyu"), _T("mixyu"), NULL } },
    { _T("みぇ"), { _T("mye"), _T("mile"), _T("mixe"), _T("milye"), _T("mixye"), NULL } },
    { _T("みょ"), { _T("myo"), _T("milyo"), _T("mixyo"), NULL } },
    { _T("りゃ"), { _T("rya"), _T("rilya"), _T("rixya"), NULL } },
    { _T("りぃ"), { _T("ryi"), _T("rili"), _T("rixi"), _T("rilyi"), _T("rixyi"), NULL } },
    { _T("りゅ"), { _T("ryu"), _T("rilyu"), _T("rixyu"), NULL } },
    { _T("りぇ"), { _T("rye"), _T("rile"), _T("rixe"), _T("rilye"), _T("rixye"), NULL } },
    { _T("りょ"), { _T("ryo"), _T("rilyo"), _T("rixyo"), NULL } },
    { _T("うぁ"), { _T("wha"), _T("ula"), _T("uxa"), _T("wula"), _T("wuxa"), _T("whula"), _T("whuxa"), NULL } },
    { _T("うぃ"), { _T("wi"), _T("whi"), _T("uli"), _T("uxi"), _T("ulyi"), _T("uxyi"), _T("wuli"), _T("wuxi"), _T("wulyi"), _T("wuxyi"), _T("whuli"), NULL } },
    { _T("うぇ"), { _T("we"), _T("whe"), _T("ule"), _T("uxe"), _T("ulye"), _T("uxye"), _T("wule"), _T("wuxe"), _T("wulye"), _T("wuxye"), _T("whule"), _T("whuxe"), _T("whulye"), _T("whuxye"), NULL } },
    { _T("うぉ"), { _T("who"), _T("ulo"), _T("uxo"), _T("wulo"), _T("wuxo"), _T("whulo"), _T("whuxo"), NULL } },
    { _T("ゔぁ"), { _T("va"), _T("vula"), _T("vuxa"), NULL } },
    { _T("ゔぃ"), { _T("vi"), _T("vyi"), _T("vuli"), _T("vuxi"), _T("vulyi"), _T("vuxyi"), NULL } },
    { _T("ゔ"), { _T("vu"), NULL } },
    { _T("ゔぇ"), { _T("ve"), _T("vye"), _T("vule"), _T("vuxe"), _T("vulye"), _T("vuxye"), NULL } },
    { _T("ゔぉ"), { _T("vo"), _T("vulo"), _T("vuxo"), NULL } },
    { _T("ゔゃ"), { _T("vya"), _T("vulya"), _T("vuxya"), NULL } },
    { _T("ゔゅ"), { _T("vyu"), _T("vulyu"), _T("vuxyu"), NULL } },
    { _T("ゔょ"), { _T("vyo"), _T("vulyo"), _T("vuxyo"), NULL } },
    { _T("ヴぁ"), { _T("va"), _T("vula"), _T("vuxa"), NULL } },
    { _T("ヴぃ"), { _T("vi"), _T("vyi"), _T("vuli"), _T("vuxi"), _T("vulyi"), _T("vuxyi"), NULL } },
    { _T("ヴ"), { _T("vu"), NULL } },
    { _T("ヴぇ"), { _T("ve"), _T("vye"), _T("vule"), _T("vuxe"), _T("vulye"), _T("vuxye"), NULL } },
    { _T("ヴぉ"), { _T("vo"), _T("vulo"), _T("vuxo"), NULL } },
    { _T("ヴゃ"), { _T("vya"), _T("vulya"), _T("vuxya"), NULL } },
    { _T("ヴゅ"), { _T("vyu"), _T("vulyu"), _T("vuxyu"), NULL } },
    { _T("ヴょ"), { _T("vyo"), _T("vulyo"), _T("vuxyo"), NULL } },
    { _T("ゐ"), { _T("wyi"), NULL } },
    { _T("ゑ"), { _T("wye"), NULL } },
    { _T("んか"), { _T("nka"), _T("nca"), _T("nnka"), _T("nnca"), _T("xnka"), _T("xnca"), NULL } },
    { _T("んき"), { _T("nki"), _T("nnki"), _T("xnki"), NULL } },
    { _T("んく"), { _T("nku"), _T("ncu"), _T("nqu"), _T("nnku"), _T("nncu"), _T("nnqu"), _T("xnku"), _T("xncu"), _T("xnqu"), NULL } },
    { _T("んけ"), { _T("nke"), _T("nnke"), _T("xnke"), NULL } },
    { _T("んこ"), { _T("nko"), _T("nco"), _T("nnko"), _T("nnco"), _T("xnko"), _T("xnco"), NULL } },
    { _T("んさ"), { _T("nsa"), _T("nnsa"), _T("xnsa"), NULL } },
    { _T("んし"), { _T("nsi"), _T("nshi"), _T("nci"), _T("nnsi"), _T("nnshi"), _T("nnci"), _T("xnsi"), _T("xnshi"), _T("xnci"), NULL } },
    { _T("んす"), { _T("nsu"), _T("nnsu"), _T("xnsu"), NULL } },
    { _T("んせ"), { _T("nse"), _T("nce"), _T("nnse"), _T("nnce"), _T("xnse"), _T("xnce"), NULL } },
    { _T("んそ"), { _T("nso"), _T("nnso"), _T("xnso"), NULL } },
    { _T("んた"), { _T("nta"), _T("nnta"), _T("xnta"), NULL } },
    { _T("んち"), { _T("nti"), _T("nchi"), _T("nnti"), _T("nnchi"), _T("xnti"), _T("xnchi"), NULL } },
    { _T("んつ"), { _T("ntu"), _T("ntsu"), _T("nntu"), _T("nntsu"), _T("xntu"), _T("xntsu"), NULL } },
    { _T("んて"), { _T("nte"), _T("nnte"), _T("xnte"), NULL } },
    { _T("んと"), { _T("nto"), _T("nnto"), _T("xnto"), NULL } },
    { _T("んは"), { _T("nha"), _T("nnha"), _T("xnha"), NULL } },
    { _T("んひ"), { _T("nhi"), _T("nnhi"), _T("xnhi"), NULL } },
    { _T("んふ"), { _T("nfu"), _T("nhu"), _T("nnfu"), _T("nnhu"), _T("xnfu"), _T("xnhu"), NULL } },
    { _T("んへ"), { _T("nhe"), _T("nnhe"), _T("xnhe"), NULL } },
    { _T("んほ"), { _T("nho"), _T("nnho"), _T("xnho"), NULL } },
    { _T("んま"), { _T("nma"), _T("nnma"), _T("xnma"), NULL } },
    { _T("んみ"), { _T("nmi"), _T("nnmi"), _T("xnmi"), NULL } },
    { _T("んむ"), { _T("nmu"), _T("nnmu"), _T("xnmu"), NULL } },
    { _T("んめ"), { _T("nme"), _T("nnme"), _T("xnme"), NULL } },
    { _T("んも"), { _T("nmo"), _T("nnmo"), _T("xnmo"), NULL } },
    { _T("んら"), { _T("nra"), _T("nnra"), _T("xnra"), NULL } },
    { _T("んり"), { _T("nri"), _T("nnri"), _T("xnri"), NULL } },
    { _T("んる"), { _T("nru"), _T("nnru"), _T("xnru"), NULL } },
    { _T("んれ"), { _T("nre"), _T("nnre"), _T("xnre"), NULL } },
    { _T("んろ"), { _T("nro"), _T("nnro"), _T("xnro"), NULL } },
    { _T("んわ"), { _T("nwa"), _T("nnwa"), _T("xnwa"), NULL } },
    { _T("んを"), { _T("nwo"), _T("nnwo"), _T("xnwo"), NULL } },
    { _T("んが"), { _T("nga"), _T("nnga"), _T("xnga"), NULL } },
    { _T("んぎ"), { _T("ngi"), _T("nngi"), _T("xngi"), NULL } },
    { _T("んぐ"), { _T("ngu"), _T("nngu"), _T("xngu"), NULL } },
    { _T("んげ"), { _T("nge"), _T("nnge"), _T("xnge"), NULL } },
    { _T("んご"), { _T("ngo"), _T("nngo"), _T("xngo"), NULL } },
    { _T("んざ"), { _T("nza"), _T("nnza"), _T("xnza"), NULL } },
    { _T("んじ"), { _T("nji"), _T("nzi"), _T("nnji"), _T("nnzi"), _T("xnji"), _T("xnzi"), NULL } },
    { _T("んず"), { _T("nzu"), _T("nnzu"), _T("xnzu"), NULL } },
    { _T("んぜ"), { _T("nze"), _T("nnze"), _T("xnze"), NULL } },
    { _T("んぞ"), { _T("nzo"), _T("nnzo"), _T("xnze"), NULL } },
    { _T("んだ"), { _T("nda"), _T("nnda"), _T("xnda"), NULL } },
    { _T("んぢ"), { _T("ndi"), _T("nndi"), _T("xndi"), NULL } },
    { _T("んづ"), { _T("ndu"), _T("nndu"), _T("xndu"), NULL } },
    { _T("んで"), { _T("nde"), _T("nnde"), _T("xnde"), NULL } },
    { _T("んど"), { _T("ndo"), _T("nndo"), _T("xndo"), NULL } },
    { _T("んば"), { _T("nba"), _T("nnba"), _T("xnba"), NULL } },
    { _T("んび"), { _T("nbi"), _T("nnbi"), _T("xnbi"), NULL } },
    { _T("んぶ"), { _T("nbu"), _T("nnbu"), _T("xnbu"), NULL } },
    { _T("んべ"), { _T("nbe"), _T("nnbe"), _T("xnbe"), NULL } },
    { _T("んぼ"), { _T("nbo"), _T("nnbo"), _T("xnbo"), NULL } },
    { _T("んぱ"), { _T("npa"), _T("nnpa"), _T("xnpa"), NULL } },
    { _T("んぴ"), { _T("npi"), _T("nnpi"), _T("xnpi"), NULL } },
    { _T("んぷ"), { _T("npu"), _T("nnpu"), _T("xnpu"), NULL } },
    { _T("んぺ"), { _T("npe"), _T("nnpe"), _T("xnpe"), NULL } },
    { _T("んぽ"), { _T("npo"), _T("nnpo"), _T("xnpo"), NULL } },
    { _T("んきゃ"), { _T("nkya"), _T("nkilya"), _T("nkixya"), _T("nnkya"), _T("nnkilya"), _T("nnkixya"), _T("xnkya"), _T("xnkilya"), _T("xnkixya"), NULL } },
    { _T("んきぃ"), { _T("nkyi"), _T("nkili"), _T("nkilyi"), _T("nkixi"), _T("nkixyi"), _T("nnkyi"), _T("nnkili"), _T("nnkilyi"), _T("nnkixi"), _T("nnkixyi"), _T("xnkyi"), _T("xnkili"), _T("xnkilyi"), _T("xnkixi"), _T("xnkixyi"), NULL } },
    { _T("んきゅ"), { _T("nkyu"), _T("nkilyu"), _T("nkixyu"), _T("nnkyu"), _T("nnkilyu"), _T("nnkixyu"), _T("xnkyu"), _T("xnkilyu"), _T("xnkixyu"), NULL } },
    { _T("んきぇ"), { _T("nkye"), _T("nkile"), _T("nkilye"), _T("nkixe"), _T("nkixye"), _T("nnkye"), _T("nnkile"), _T("nnkilye"), _T("nnkixe"), _T("nnkixye"), _T("xnkye"), _T("xnkile"), _T("xnkilye"), _T("xnkixe"), _T("xnkixye"), NULL } },
    { _T("んきょ"), { _T("nkyo"), _T("nkilyo"), _T("nkixyo"), _T("nnkyo"), _T("nnkilyo"), _T("nnkixyo"), _T("xnkyo"), _T("xnkilyo"), _T("xnkixyo"), NULL } },
    { _T("んぎゃ"), { _T("ngya"), _T("ngilya"), _T("ngixya"), _T("nngya"), _T("nngilya"), _T("nngixya"), _T("xngya"), _T("xngilya"), _T("xngixya"), NULL } },
    { _T("んぎぃ"), { _T("ngyi"), _T("ngili"), _T("ngilyi"), _T("ngixi"), _T("ngixyi"), _T("nngyi"), _T("nngili"), _T("nngilyi"), _T("nngixi"), _T("nngixyi"), _T("xngyi"), _T("xngili"), _T("xngilyi"), _T("xngixi"), _T("xngixyi"), NULL } },
    { _T("んぎゅ"), { _T("ngyu"), _T("ngilyu"), _T("ngixyu"), _T("nngyu"), _T("nngilyu"), _T("nngixyu"), _T("xngyu"), _T("xngilyu"), _T("xngixyu"), NULL } },
    { _T("んぎぇ"), { _T("ngye"), _T("ngile"), _T("ngilye"), _T("ngixe"), _T("ngixye"), _T("nngye"), _T("nngile"), _T("nngilye"), _T("nngixe"), _T("nngixye"), _T("xngye"), _T("xngile"), _T("xngilye"), _T("xngixe"), _T("xngixye"), NULL } },
    { _T("んぎょ"), { _T("ngyo"), _T("ngilyo"), _T("ngixyo"), _T("nngyo"), _T("nngilyo"), _T("nngixyo"), _T("xngyo"), _T("xngilyo"), _T("xngixyo"), NULL } },
    { _T("んしゃ"), { _T("nsya"), _T("nsha"), _T("nsilya"), _T("nsixya"), _T("nshilya"), _T("nshixya"), _T("ncilya"), _T("ncixya"), _T("nnsya"), _T("nnsha"), _T("nnsilya"), _T("nnsixya"), _T("nnshilya"), _T("nnshixya"), _T("nncilya"), _T("nncixya"), _T("xnsya"), _T("xnsha"), _T("xnsilya"), _T("xnsixya"), _T("xnshilya"), _T("xnshixya"), _T("xncilya"), _T("xncixya"), NULL } },
    { _T("んしぃ"), { _T("nsyi"), _T("nsili"), _T("nsixi"), _T("nsilyi"), _T("nsixyi"), _T("nshili"), _T("nshixi"), _T("nshilyi"), _T("nshixyi"), _T("ncili"), _T("ncixi"), _T("ncilyi"), _T("ncixyi"), _T("nnsyi"), _T("nnsili"), _T("nnsixi"), _T("nnsilyi"), _T("nnsixyi"), _T("nnshili"), _T("nnshixi"), _T("nnshilyi"), _T("nnshixyi"), _T("nncili"), _T("nncixi"), _T("nncilyi"), _T("nncixyi"), _T("xnsyi"), _T("xnsili"), _T("xnsixi"), _T("xnsilyi"), _T("xnsixyi"), _T("xnshili"), _T("xnshixi"), _T("xnshilyi"), _T("xnshixyi"), _T("xncili"), _T("xncixi"), _T("xncilyi"), _T("xncixyi"), NULL } },
    { _T("んしゅ"), { _T("nsyu"), _T("nshu"), _T("nsilyu"), _T("nsixyu"), _T("nshilyu"), _T("nshixyu"), _T("ncilyu"), _T("ncixyu"), _T("nnsyu"), _T("nnshu"), _T("nnsilyu"), _T("nnsixyu"), _T("nnshilyu"), _T("nnshixyu"), _T("nncilyu"), _T("nncixyu"), _T("xnsyu"), _T("xnshu"), _T("xnsilyu"), _T("xnsixyu"), _T("xnshilyu"), _T("xnshixyu"), _T("xncilyu"), _T("xncixyu"), NULL } },
    { _T("んしぇ"), { _T("nsye"), _T("nshe"), _T("nsile"), _T("nsilye"), _T("nsixe"), _T("nsixye"), _T("nshile"), _T("nshilye"), _T("nshixe"), _T("nshixye"), _T("ncile"), _T("ncilye"), _T("ncixe"), _T("ncixye"), _T("nnsye"), _T("nnshe"), _T("nnsile"), _T("nnsilye"), _T("nnsixe"), _T("nnsixye"), _T("nnshile"), _T("nnshilye"), _T("nnshixe"), _T("nnshixye"), _T("nncile"), _T("nncilye"), _T("nncixe"), _T("nncixye"), _T("xnsye"), _T("xnshe"), _T("xnsile"), _T("xnsilye"), _T("xnsixe"), _T("xnsixye"), _T("xnshile"), _T("xnshilye"), _T("xnshixe"), _T("xnshixye"), _T("xncile"), _T("xncilye"), _T("xncixe"), _T("xncixye"), NULL } },
    { _T("んしょ"), { _T("nsyo"), _T("nsho"), _T("nsilyo"), _T("nsixyo"), _T("nshilyo"), _T("nshixyo"), _T("ncilyo"), _T("ncixyo"), _T("nnsyo"), _T("nnsho"), _T("nnsilyo"), _T("nnsixyo"), _T("nnshilyo"), _T("nnshixyo"), _T("nncilyo"), _T("nncixyo"), _T("xnsyo"), _T("xnsho"), _T("xnsilyo"), _T("xnsixyo"), _T("xnshilyo"), _T("xnshixyo"), _T("xncilyo"), _T("xncixyo"), NULL } },
    { _T("んじゃ"), { _T("nja"), _T("njya"), _T("nzya"), _T("njilya"), _T("njixya"), _T("nzilya"), _T("nzixya"), _T("nnja"), _T("nnjya"), _T("nnzya"), _T("nnjilya"), _T("nnjixya"), _T("nnzilya"), _T("nnzixya"), _T("xnja"), _T("xnjya"), _T("xnzya"), _T("xnjilya"), _T("xnjixya"), _T("xnzilya"), _T("xnzixya"), NULL } },
    { _T("んじぃ"), { _T("njyi"), _T("nzyi"), _T("njili"), _T("njixi"), _T("njilyi"), _T("njixyi"), _T("nzili"), _T("nzixi"), _T("nzilyi"), _T("nzixyi"), _T("nnjyi"), _T("nnzyi"), _T("nnjili"), _T("nnjixi"), _T("nnjilyi"), _T("nnjixyi"), _T("nnzili"), _T("nnzixi"), _T("nnzilyi"), _T("nnzixyi"), _T("xnjyi"), _T("xnzyi"), _T("xnjili"), _T("xnjixi"), _T("xnjilyi"), _T("xnjixyi"), _T("xnzili"), _T("xnzixi"), _T("xnzilyi"), _T("xnzixyi"), NULL } },
    { _T("んじゅ"), { _T("nju"), _T("njyu"), _T("nzyu"), _T("njilyu"), _T("njixyu"), _T("nzilyu"), _T("nzixyu"), _T("nnju"), _T("nnjyu"), _T("nnzyu"), _T("nnjilyu"), _T("nnjixyu"), _T("nnzilyu"), _T("nnzixyu"), _T("xnju"), _T("xnjyu"), _T("xnzyu"), _T("xnjilyu"), _T("xnjixyu"), _T("xnzilyu"), _T("xnzixyu"), NULL } },
    { _T("んじぇ"), { _T("nje"), _T("njye"), _T("nzye"), _T("njile"), _T("njixe"), _T("njilye"), _T("njixye"), _T("nzile"), _T("nzixe"), _T("nzilye"), _T("nzixye"), _T("nnje"), _T("nnjye"), _T("nnzye"), _T("nnjile"), _T("nnjixe"), _T("nnjilye"), _T("nnjixye"), _T("nnzile"), _T("nnzixe"), _T("nnzilye"), _T("nnzixye"), _T("xnje"), _T("xnjye"), _T("xnzye"), _T("xnjile"), _T("xnjixe"), _T("xnjilye"), _T("xnjixye"), _T("xnzile"), _T("xnzixe"), _T("xnzilye"), _T("xnzixye"), NULL } },
    { _T("んじょ"), { _T("njo"), _T("njyo"), _T("nzyo"), _T("njilyo"), _T("njixyo"), _T("nzilyo"), _T("nzixyo"), _T("nnjo"), _T("nnjyo"), _T("nnzyo"), _T("nnjilyo"), _T("nnjixyo"), _T("nnzilyo"), _T("nnzixyo"), _T("xnjo"), _T("xnjyo"), _T("xnzyo"), _T("xnjilyo"), _T("xnjixyo"), _T("xnzilyo"), _T("xnzixyo"), NULL } },
    { _T("んちゃ"), { _T("ntya"), _T("ncha"), _T("ncya"), _T("ntilya"), _T("ntixya"), _T("nchilya"), _T("nchixya"), _T("nntya"), _T("nncha"), _T("nncya"), _T("nntilya"), _T("nntixya"), _T("nnchilya"), _T("nnchixya"), _T("xntya"), _T("xncha"), _T("xncya"), _T("xntilya"), _T("xntixya"), _T("xnchilya"), _T("xnchixya"), NULL } },
    { _T("んちぃ"), { _T("ntyi"), _T("ncyi"), _T("ntili"), _T("ntixi"), _T("ntilyi"), _T("ntixyi"), _T("nchili"), _T("nchixi"), _T("nchilyi"), _T("nchixyi"), _T("nntyi"), _T("nncyi"), _T("nntili"), _T("nntixi"), _T("nntilyi"), _T("nntixyi"), _T("nnchili"), _T("nnchixi"), _T("nnchilyi"), _T("nnchixyi"), _T("xntyi"), _T("xncyi"), _T("xntili"), _T("xntixi"), _T("xntilyi"), _T("xntixyi"), _T("xnchili"), _T("xnchixi"), _T("xnchilyi"), _T("xnchixyi"), NULL } },
    { _T("んちゅ"), { _T("ntyu"), _T("nchu"), _T("ncyu"), _T("ntilyu"), _T("ntixyu"), _T("nchilyu"), _T("nchixyu"), _T("nntyu"), _T("nnchu"), _T("nncyu"), _T("nntilyu"), _T("nntixyu"), _T("nnchilyu"), _T("nnchixyu"), _T("xntyu"), _T("xnchu"), _T("xncyu"), _T("xntilyu"), _T("xntixyu"), _T("xnchilyu"), _T("xnchixyu"), NULL } },
    { _T("んちぇ"), { _T("ntye"), _T("nche"), _T("ncye"), _T("ntile"), _T("ntixe"), _T("ntilye"), _T("ntixye"), _T("nchile"), _T("nchixe"), _T("nchilye"), _T("nchixye"), _T("nntye"), _T("nnche"), _T("nncye"), _T("nntile"), _T("nntixe"), _T("nntilye"), _T("nntixye"), _T("nnchile"), _T("nnchixe"), _T("nnhilye"), _T("nnchixye"), _T("xntye"), _T("xnche"), _T("xncye"), _T("xntile"), _T("xntixe"), _T("xntilye"), _T("xntixye"), _T("xnchile"), _T("xnchixe"), _T("xnchilye"), _T("xnchixye"), NULL } },
    { _T("んちょ"), { _T("ntyo"), _T("ncho"), _T("ncyo"), _T("ntilyo"), _T("ntixyo"), _T("nchilyo"), _T("nchixyo"), _T("nntyo"), _T("nncho"), _T("nncyo"), _T("nntilyo"), _T("nntixyo"), _T("nnchilyo"), _T("nnchixyo"), _T("xntyo"), _T("xncho"), _T("xncyo"), _T("xntilyo"), _T("xntixyo"), _T("xnchilyo"), _T("xnchixyo"), NULL } },
    { _T("んぢぃ"), { _T("ndyi"), _T("nndyi"), _T("xndyi"), _T("ndilyi"), _T("nndilyi"), _T("xndilyi"), _T("ndixyi"), _T("nndixyi"), _T("xndixyi"), NULL } },
    { _T("んぢゃ"), { _T("ndya"), _T("ndilya"), _T("ndixya"), _T("nndya"), _T("nndilya"), _T("nndixya"), _T("xndya"), _T("xndilya"), _T("xndixya"), NULL } },
    { _T("んぢゅ"), { _T("ndyu"), _T("ndilyu"), _T("ndixyu"), _T("nndyu"), _T("nndilyu"), _T("nndixyu"), _T("xndyu"), _T("xndilyu"), _T("xndixyu"), NULL } },
    { _T("んぢぇ"), { _T("ndye"), _T("ndile"), _T("ndixe"), _T("ndilye"), _T("ndixye"), _T("nndye"), _T("nndile"), _T("nndixe"), _T("nndilye"), _T("nndixye"), _T("xndye"), _T("xndile"), _T("xndixe"), _T("xndilye"), _T("xndixye"), NULL } },
    { _T("んぢょ"), { _T("ndyo"), _T("ndilyo"), _T("ndixyo"), _T("nndyo"), _T("nndilyo"), _T("nndixyo"), _T("xndyo"), _T("xndilyo"), _T("xndixyo"), NULL } },
    { _T("んつぁ"), { _T("ntsa"), _T("ntula"), _T("ntuxa"), _T("ntsula"), _T("ntsuxa"), _T("nntsa"), _T("nntula"), _T("nntuxa"), _T("nntsula"), _T("nntsuxa"), _T("xntsa"), _T("xntula"), _T("xntuxa"), _T("xntsula"), _T("xntsuxa"), NULL } },
    { _T("んつぃ"), { _T("ntsi"), _T("ntuli"), _T("ntuxi"), _T("ntulyi"), _T("ntuxyi"), _T("ntsuli"), _T("ntsuxi"), _T("ntsulyi"), _T("ntsuxyi"), _T("nntsi"), _T("nntuli"), _T("nntuxi"), _T("nntulyi"), _T("nntuxyi"), _T("nntsuli"), _T("nntsuxi"), _T("nntsulyi"), _T("nntsuxyi"), _T("xntsi"), _T("xntuli"), _T("xntuxi"), _T("xntulyi"), _T("xntuxyi"), _T("xntsuli"), _T("xntsuxi"), _T("xntsulyi"), _T("xntsuxyi"), NULL } },
    { _T("んつぇ"), { _T("ntse"), _T("ntule"), _T("ntuxe"), _T("ntulye"), _T("ntuxye"), _T("ntsule"), _T("ntsuxe"), _T("ntsulye"), _T("ntsuxye"), _T("nntse"), _T("nntule"), _T("nntuxe"), _T("nntulye"), _T("nntuxye"), _T("nntsule"), _T("nntsuxe"), _T("nntsulye"), _T("nntsuxye"), _T("xntse"), _T("xntule"), _T("xntuxe"), _T("xntulye"), _T("xntuxye"), _T("xntsule"), _T("xntsuxe"), _T("xntsulye"), _T("xntsuxye"), NULL } },
    { _T("んつぉ"), { _T("ntso"), _T("ntulo"), _T("ntuxo"), _T("ntsulo"), _T("ntsuxo"), _T("nntso"), _T("nntulo"), _T("nntuxo"), _T("nntsulo"), _T("nntsuxo"), _T("xntso"), _T("xntulo"), _T("xntuxo"), _T("xntsulo"), _T("xntsuxo"), NULL } },
    { _T("んてゃ"), { _T("ntha"), _T("ntelya"), _T("ntexya"), _T("nntha"), _T("nntelya"), _T("nntexya"), _T("xntha"), _T("xntelya"), _T("xntexya"), NULL } },
    { _T("んてぃ"), { _T("nthi"), _T("nteli"), _T("ntexi"), _T("ntelyi"), _T("ntexyi"), _T("nnthi"), _T("nnteli"), _T("nntexi"), _T("nntelyi"), _T("nntexyi"), _T("xnthi"), _T("xnteli"), _T("xntexi"), _T("xntelyi"), _T("xntexyi"), NULL } },
    { _T("んてゅ"), { _T("nthu"), _T("ntelyu"), _T("ntexyu"), _T("nnthu"), _T("nntelyu"), _T("nntexyu"), _T("xnthu"), _T("xntelyu"), _T("xntexyu"), NULL } },
    { _T("んてぇ"), { _T("nthe"), _T("ntele"), _T("ntexe"), _T("ntelye"), _T("ntexye"), _T("nnthe"), _T("nntele"), _T("nntexe"), _T("nntelye"), _T("nntexye"), _T("xnthe"), _T("xntele"), _T("xntexe"), _T("xntelye"), _T("xntexye"), NULL } },
    { _T("んてょ"), { _T("ntho"), _T("ntelyo"), _T("ntexyo"), _T("nntho"), _T("nntelyo"), _T("nntexyo"), _T("xntho"), _T("xntelyo"), _T("xntexyo"), NULL } },
    { _T("んでゃ"), { _T("ndha"), _T("ndelya"), _T("ndexya"), _T("nndha"), _T("nndelya"), _T("nndexya"), _T("xndha"), _T("xndelya"), _T("xndexya"), NULL } },
    { _T("んでぃ"), { _T("ndhi"), _T("ndeli"), _T("ndexi"), _T("ndelyi"), _T("ndexyi"), _T("nndhi"), _T("nndeli"), _T("nndexi"), _T("nndelyi"), _T("nndexyi"), _T("xndhi"), _T("xndeli"), _T("xndexi"), _T("xndelyi"), _T("xndexyi"), NULL } },
    { _T("んでゅ"), { _T("ndhu"), _T("ndelyu"), _T("ndexyu"), _T("nndhu"), _T("nndelyu"), _T("nndexyu"), _T("xndhu"), _T("xndelyu"), _T("xndexyu"), NULL } },
    { _T("んでぇ"), { _T("ndhe"), _T("ndele"), _T("ndexe"), _T("ndelye"), _T("ndexye"), _T("nndhe"), _T("nndele"), _T("nndexe"), _T("nndelye"), _T("nndexye"), _T("xndhe"), _T("xndele"), _T("xndexe"), _T("xndelye"), _T("xndexye"), NULL } },
    { _T("んでょ"), { _T("ndho"), _T("ndelyo"), _T("ndexyo"), _T("nndho"), _T("nndelyo"), _T("nndexyo"), _T("xndho"), _T("xndelyo"), _T("xndexyo"), NULL } },
    { _T("んとぁ"), { _T("ntwa"), _T("ntola"), _T("ntoxa"), _T("nntwa"), _T("nntola"), _T("nntoxa"), _T("xntwa"), _T("xntola"), _T("xntoxa"), NULL } },
    { _T("んとぃ"), { _T("ntwi"), _T("ntoli"), _T("ntoxi"), _T("ntolyi"), _T("ntoxyi"), _T("nntwi"), _T("nntoli"), _T("nntoxi"), _T("nntolyi"), _T("nntoxyi"), _T("xntwi"), _T("xntoli"), _T("xntoxi"), _T("xntolyi"), _T("xntoxyi"), NULL } },
    { _T("んとぅ"), { _T("ntwu"), _T("ntolu"), _T("ntoxu"), _T("nntwu"), _T("nntolu"), _T("nntoxu"), _T("xntwu"), _T("xntolu"), _T("xntoxu"), NULL } },
    { _T("んとぇ"), { _T("ntwe"), _T("ntole"), _T("ntoxe"), _T("ntolye"), _T("ntoxye"), _T("nntwe"), _T("nntole"), _T("nntoxe"), _T("nntolye"), _T("nntoxye"), _T("xntwe"), _T("xntole"), _T("xntoxe"), _T("xntolye"), _T("xntoxye"), NULL } },
    { _T("んとぉ"), { _T("ntwo"), _T("ntolo"), _T("ntoxo"), _T("nntwo"), _T("nntolo"), _T("nntoxo"), _T("xntwo"), _T("xntolo"), _T("xntoxo"), NULL } },
    { _T("んどぁ"), { _T("dwa"), _T("dola"), _T("doxa"), _T("nndwa"), _T("nndola"), _T("nndoxa"), _T("xndwa"), _T("xndola"), _T("xndoxa"), NULL } },
    { _T("んどぃ"), { _T("dwi"), _T("doli"), _T("doxi"), _T("dolyi"), _T("doxyi"), _T("nndwi"), _T("nndoli"), _T("nndoxi"), _T("nndolyi"), _T("nndoxyi"), _T("xndwi"), _T("xndoli"), _T("xndoxi"), _T("xndolyi"), _T("xndoxyi"), NULL } },
    { _T("んどぅ"), { _T("dwu"), _T("dolu"), _T("doxu"), _T("nndwu"), _T("nndolu"), _T("nndoxu"), _T("xndwu"), _T("xndolu"), _T("xndoxu"), NULL } },
    { _T("んどぇ"), { _T("dwe"), _T("dole"), _T("doxe"), _T("dolye"), _T("doxye"), _T("nndwe"), _T("nndole"), _T("nndoxe"), _T("nndolye"), _T("nndoxye"), _T("xndwe"), _T("xndole"), _T("xndoxe"), _T("xndolye"), _T("xndoxye"), NULL } },
    { _T("んどぉ"), { _T("dwo"), _T("dolo"), _T("doxo"), _T("nndwo"), _T("nndolo"), _T("nndoxo"), _T("xndwo"), _T("xndolo"), _T("xndoxo"), NULL } },
    { _T("んぴゃ"), { _T("npya"), _T("npilya"), _T("npixya"), _T("nnpya"), _T("nnpilya"), _T("nnpixya"), _T("xnpya"), _T("xnpilya"), _T("xnpixya"), NULL } },
    { _T("んぴぃ"), { _T("npyi"), _T("npili"), _T("npixi"), _T("npilyi"), _T("npixyi"), _T("nnpyi"), _T("nnpili"), _T("nnpixi"), _T("nnpilyi"), _T("nnpixyi"), _T("xnpyi"), _T("xnpili"), _T("xnpixi"), _T("xnpilyi"), _T("xnpixyi"), NULL } },
    { _T("んぴゅ"), { _T("npyu"), _T("npilyu"), _T("npixyu"), _T("nnpyu"), _T("nnpilyu"), _T("nnpixyu"), _T("xnpyu"), _T("xnpilyu"), _T("xnpixyu"), NULL } },
    { _T("んぴぇ"), { _T("npye"), _T("npile"), _T("npixe"), _T("npilye"), _T("npixye"), _T("nnpye"), _T("nnpile"), _T("nnpixe"), _T("nnpilye"), _T("nnpixye"), _T("xnpye"), _T("xnpile"), _T("xnpixe"), _T("xnpilye"), _T("xnpixye"), NULL } },
    { _T("んぴょ"), { _T("npyo"), _T("npilyo"), _T("npixyo"), _T("nnpyo"), _T("nnpilyo"), _T("nnpixyo"), _T("xnpyo"), _T("xnpilyo"), _T("xnpixyo"), NULL } },
    { _T("んひゃ"), { _T("nhya"), _T("nhilya"), _T("nhixya"), _T("nnhya"), _T("nnhilya"), _T("nnhixya"), _T("xnhya"), _T("xnhilya"), _T("xnhixya"), NULL } },
    { _T("んひぃ"), { _T("nhyi"), _T("nhili"), _T("nhixi"), _T("nhilyi"), _T("nhixyi"), _T("nnhyi"), _T("nnhili"), _T("nnhixi"), _T("nnhilyi"), _T("nnhixyi"), _T("xnhyi"), _T("xnhili"), _T("xnhixi"), _T("xnhilyi"), _T("xnhixyi"), NULL } },
    { _T("んひゅ"), { _T("nhyu"), _T("nhilyu"), _T("nhixyu"), _T("nnhyu"), _T("nnhilyu"), _T("nnhixyu"), _T("xnhyu"), _T("xnhilyu"), _T("xnhixyu"), NULL } },
    { _T("んひぇ"), { _T("nhye"), _T("nhile"), _T("nhixe"), _T("nhilye"), _T("nhixye"), _T("nnhye"), _T("nnhile"), _T("nnhixe"), _T("nnhilye"), _T("nnhixye"), _T("xnhye"), _T("xnhile"), _T("xnhixe"), _T("xnhilye"), _T("xnhixye"), NULL } },
    { _T("んひょ"), { _T("nhyo"), _T("nhilyo"), _T("nhixyo"), _T("nnhyo"), _T("nnhilyo"), _T("nnhixyo"), _T("xnhyo"), _T("xnhilyo"), _T("xnhixyo"), NULL } },
    { _T("んびゃ"), { _T("nbya"), _T("nbilya"), _T("nbixya"), _T("nnbya"), _T("nnbilya"), _T("nnbixya"), _T("xnbya"), _T("xnbilya"), _T("xnbixya"), NULL } },
    { _T("んびぃ"), { _T("nbyi"), _T("nbili"), _T("nbixi"), _T("nbilyi"), _T("nbixyi"), _T("nnbyi"), _T("nnbili"), _T("nnbixi"), _T("nnbilyi"), _T("nnbixyi"), _T("xnbyi"), _T("xnbili"), _T("xnbixi"), _T("xnbilyi"), _T("xnbixyi"), NULL } },
    { _T("んびゅ"), { _T("nbyu"), _T("nbilyu"), _T("nbixyu"), _T("nnbyu"), _T("nnbilyu"), _T("nnbixyu"), _T("xnbyu"), _T("xnbilyu"), _T("xnbixyu"), NULL } },
    { _T("んびぇ"), { _T("nbye"), _T("nbile"), _T("nbixe"), _T("nbilye"), _T("nbixye"), _T("nnbye"), _T("nnbile"), _T("nnbixe"), _T("nnbilye"), _T("nnbixye"), _T("xnbye"), _T("xnbile"), _T("xnbixe"), _T("xnbilye"), _T("xnbixye"), NULL } },
    { _T("んびょ"), { _T("nbyo"), _T("nbilyo"), _T("nbixyo"), _T("nnbyo"), _T("nnbilyo"), _T("nnbixyo"), _T("xnbyo"), _T("xnbilyo"), _T("xnbixyo"), NULL } },
    { _T("んふゃ"), { _T("nfya"), _T("nfulya"), _T("nfuxya"), _T("nhulya"), _T("nhuxya"), _T("nnfya"), _T("nnfulya"), _T("nnfuxya"), _T("nnhulya"), _T("nnhuxya"), _T("xnfya"), _T("xnfulya"), _T("xnfuxya"), _T("xnhulya"), _T("xnhuxya"), NULL } },
    { _T("んふぃ"), { _T("nfi"), _T("nfyi"), _T("nfuli"), _T("nfuxi"), _T("nfulyi"), _T("nfuxyi"), _T("nhuli"), _T("nhuxi"), _T("nhulyi"), _T("nhuxyi"), _T("nnfi"), _T("nnfyi"), _T("nnfuli"), _T("nnfuxi"), _T("nnfulyi"), _T("nnfuxyi"), _T("nnhuli"), _T("nnhuxi"), _T("nnhulyi"), _T("nnhuxyi"), _T("xnfi"), _T("xnfyi"), _T("xnfuli"), _T("xnfuxi"), _T("xnfulyi"), _T("xnfuxyi"), _T("xnhuli"), _T("xnhuxi"), _T("xnhulyi"), _T("xnhuxyi"), NULL } },
    { _T("んふゅ"), { _T("nfyu"), _T("nfulyu"), _T("nfuxyu"), _T("nhulyu"), _T("nhuxyu"), _T("nnfyu"), _T("nnfulyu"), _T("nnfuxyu"), _T("nnhulyu"), _T("nnhuxyu"), _T("xnfyu"), _T("xnfulyu"), _T("xnfuxyu"), _T("xnhulyu"), _T("xnhuxyu"), NULL } },
    { _T("んふぇ"), { _T("nfe"), _T("nfye"), _T("nfule"), _T("nfuxe"), _T("nfulye"), _T("nfuxye"), _T("nhule"), _T("nhuxe"), _T("nhulye"), _T("nhuxye"), _T("nnfe"), _T("nnfye"), _T("nnfule"), _T("nnfuxe"), _T("nnfulye"), _T("nnfuxye"), _T("nnhule"), _T("nnhuxe"), _T("nnhulye"), _T("nnhuxye"), _T("xnfe"), _T("xnfye"), _T("xnfule"), _T("xnfuxe"), _T("xnfulye"), _T("xnfuxye"), _T("xnhule"), _T("xnhuxe"), _T("xnhulye"), _T("xnhuxye"), NULL } },
    { _T("んふょ"), { _T("nfyo"), _T("nfulyo"), _T("nfuxyo"), _T("nhulyo"), _T("nhuxyo"), _T("nnfyo"), _T("nnfulyo"), _T("nnfuxyo"), _T("nnhulyo"), _T("nnhuxyo"), _T("xnfyo"), _T("xnfulyo"), _T("xnfuxyo"), _T("xnhulyo"), _T("xnhuxyo"), NULL } },
    { _T("んふぁ"), { _T("nfa"), _T("nfula"), _T("nfuxa"), _T("nhula"), _T("nhuxa"), _T("nnfa"), _T("nnfula"), _T("nnfuxa"), _T("nnhula"), _T("nnhuxa"), _T("xnfa"), _T("xnfula"), _T("xnfuxa"), _T("xnhula"), _T("xnhuxa"), NULL } },
    { _T("んふぉ"), { _T("nfo"), _T("nfulo"), _T("nfuxo"), _T("nhulo"), _T("nhuxo"), _T("nnfo"), _T("nnfulo"), _T("nnfuxo"), _T("nnhulo"), _T("nnhuxo"), _T("xnfo"), _T("xnfulo"), _T("xnfuxo"), _T("xnhulo"), _T("xnhuxo"), NULL } },
    { _T("んみゃ"), { _T("nmya"), _T("nmilya"), _T("nmixya"), _T("nnmya"), _T("nnmilya"), _T("nnmixya"), _T("xnmya"), _T("xnmilya"), _T("xnmixya"), NULL } },
    { _T("んみぃ"), { _T("nmyi"), _T("nmili"), _T("nmixi"), _T("nmilyi"), _T("nmixyi"), _T("nnmyi"), _T("nnmili"), _T("nnmixi"), _T("nnmilyi"), _T("nnmixyi"), _T("xnmyi"), _T("xnmili"), _T("xnmixi"), _T("xnmilyi"), _T("xnmixyi"), NULL } },
    { _T("んみゅ"), { _T("nmyu"), _T("nmilyu"), _T("nmixyu"), _T("nnmyu"), _T("nnmilyu"), _T("nnmixyu"), _T("xnmyu"), _T("xnmilyu"), _T("xnmixyu"), NULL } },
    { _T("んみぇ"), { _T("nmye"), _T("nmile"), _T("nmixe"), _T("nmilye"), _T("nmixye"), _T("nnmye"), _T("nnmile"), _T("nnmixe"), _T("nnmilye"), _T("nnmixye"), _T("xnmye"), _T("xnmile"), _T("xnmixe"), _T("xnilye"), _T("xnmixye"), NULL } },
    { _T("んみょ"), { _T("nmyo"), _T("nmilyo"), _T("nmixyo"), _T("nnmyo"), _T("nnmilyo"), _T("nnmixyo"), _T("xnmyo"), _T("xnmilyo"), _T("xnmixyo"), NULL } },
    { _T("んりゃ"), { _T("nrya"), _T("nrilya"), _T("nrixya"), _T("nnrya"), _T("nnrilya"), _T("nnrixya"), _T("xnrya"), _T("xnrilya"), _T("xnrixya"), NULL } },
    { _T("んりぃ"), { _T("nryi"), _T("nrili"), _T("nrixi"), _T("nrilyi"), _T("nrixyi"), _T("nnryi"), _T("nnrili"), _T("nnrixi"), _T("nnrilyi"), _T("nnrixyi"), _T("xnryi"), _T("xnrili"), _T("xnrixi"), _T("xnrilyi"), _T("xnrixyi"), NULL } },
    { _T("んりゅ"), { _T("nryu"), _T("nrilyu"), _T("nrixyu"), _T("nnryu"), _T("nnrilyu"), _T("nnrixyu"), _T("xnryu"), _T("xnrilyu"), _T("xnrixyu"), NULL } },
    { _T("んりぇ"), { _T("nrye"), _T("nrile"), _T("nrixe"), _T("nrilye"), _T("nrixye"), _T("nnrye"), _T("nnrile"), _T("nnrixe"), _T("nnrilye"), _T("nnrixye"), _T("xnrye"), _T("xnrile"), _T("xnrixe"), _T("xnrilye"), _T("xnrixye"), NULL } },
    { _T("んりょ"), { _T("nryo"), _T("nrilyo"), _T("nrixyo"), _T("nnryo"), _T("nnrilyo"), _T("nnrixyo"), _T("xnryo"), _T("xnrilyo"), _T("xnrixyo"), NULL } },
    { _T("んうぁ"), { _T("nwha"), _T("nula"), _T("nuxa"), _T("nwula"), _T("nwuxa"), _T("nwhula"), _T("nwhuxa"), _T("nnwha"), _T("nnula"), _T("nnuxa"), _T("nnwula"), _T("nnwuxa"), _T("nnwhula"), _T("nnwhuxa"), _T("xnwha"), _T("xnula"), _T("xnuxa"), _T("xnwula"), _T("xnwuxa"), _T("xnwhula"), _T("xnwhuxa"), NULL } },
    { _T("んうぃ"), { _T("nwi"), _T("nwhi"), _T("nuli"), _T("nuxi"), _T("nulyi"), _T("nuxyi"), _T("nwuli"), _T("nwuxi"), _T("nwulyi"), _T("nwuxyi"), _T("nwhuli"), _T("nnwi"), _T("nnwhi"), _T("nnuli"), _T("nnuxi"), _T("nnulyi"), _T("nnuxyi"), _T("nnwuli"), _T("nnwuxi"), _T("nnwulyi"), _T("nnwuxyi"), _T("nnwhuli"), _T("xnwi"), _T("xnwhi"), _T("xnuli"), _T("xnuxi"), _T("xnulyi"), _T("xnuxyi"), _T("xnwuli"), _T("xnwuxi"), _T("xnwulyi"), _T("xnwuxyi"), _T("xnwhuli"), NULL } },
    { _T("んうぇ"), { _T("nwe"), _T("nwhe"), _T("nule"), _T("nuxe"), _T("nulye"), _T("nuxye"), _T("nwule"), _T("nwuxe"), _T("nwulye"), _T("nwuxye"), _T("nwhule"), _T("nwhuxe"), _T("nwhulye"), _T("nwhuxye"), _T("nnwe"), _T("nnwhe"), _T("nnule"), _T("nnuxe"), _T("nnulye"), _T("nnuxye"), _T("nnwule"), _T("nnwuxe"), _T("nnwulye"), _T("nnwuxye"), _T("nnwhule"), _T("nnwhuxe"), _T("nnwhulye"), _T("nnwhuxye"), _T("xnwe"), _T("xnwhe"), _T("xnule"), _T("xnuxe"), _T("xnulye"), _T("xnuxye"), _T("xnwule"), _T("xnwuxe"), _T("xnwulye"), _T("xnwuxye"), _T("xnwhule"), _T("xnwhuxe"), _T("xnwhulye"), _T("xnwhuxye"), NULL } },
    { _T("んうぉ"), { _T("nwho"), _T("nulo"), _T("nuxo"), _T("nwulo"), _T("nwuxo"), _T("nwhulo"), _T("nwhuxo"), _T("nnwho"), _T("nnulo"), _T("nnuxo"), _T("nnwulo"), _T("nnwuxo"), _T("nnwhulo"), _T("nnwhuxo"), _T("xnwho"), _T("xnulo"), _T("xnuxo"), _T("xnwulo"), _T("xnwuxo"), _T("xnwhulo"), _T("xnwhuxo"), NULL } },
    { _T("んゔぁ"), { _T("nva"), _T("nvula"), _T("nvuxa"), _T("nnva"), _T("nnvula"), _T("nnvuxa"), _T("xnva"), _T("xnvula"), _T("xnvuxa"), NULL } },
    { _T("んゔぃ"), { _T("nvi"), _T("nvyi"), _T("nvuli"), _T("nvuxi"), _T("nvulyi"), _T("nvuxyi"), _T("nnvi"), _T("nnvyi"), _T("nnvuli"), _T("nnvuxi"), _T("nnvulyi"), _T("nnvuxyi"), _T("xnvi"), _T("xnvyi"), _T("xnvuli"), _T("xnvuxi"), _T("xnvulyi"), _T("xnvuxyi"), NULL } },
    { _T("んゔ"), { _T("nvu"), _T("nnvu"), _T("xnvu"), NULL } },
    { _T("んゔぇ"), { _T("nve"), _T("nvye"), _T("nvule"), _T("nvuxe"), _T("nvulye"), _T("nvuxye"), _T("nnve"), _T("nnvye"), _T("nnvule"), _T("nnvuxe"), _T("nnvulye"), _T("nnvuxye"), _T("xnve"), _T("xnvye"), _T("xnvule"), _T("xnvuxe"), _T("xnvulye"), _T("xnvuxye"), NULL } },
    { _T("んゔぉ"), { _T("nvo"), _T("nvulo"), _T("nvuxo"), _T("nnvo"), _T("nnvulo"), _T("nnvuxo"), _T("xnvo"), _T("xnvulo"), _T("xnvuxo"), NULL } },
    { _T("んゔゃ"), { _T("nvya"), _T("nvulya"), _T("nvuxya"), _T("nnvya"), _T("nnvulya"), _T("nnvuxya"), _T("xnvya"), _T("xnvulya"), _T("xnvuxya"), NULL } },
    { _T("んゔゅ"), { _T("nvyu"), _T("nvulyu"), _T("nvuxyu"), _T("nnvyu"), _T("nnvulyu"), _T("nnvuxyu"), _T("xnvyu"), _T("xnvulyu"), _T("xnvuxyu"), NULL } },
    { _T("んゔょ"), { _T("nvyo"), _T("nvulyo"), _T("nvuxyo"), _T("nnvyo"), _T("nnvulyo"), _T("nnvuxyo"), _T("xnvyo"), _T("xnvulyo"), _T("xnvuxyo"), NULL } },
    { _T("んヴぁ"), { _T("nva"), _T("nvula"), _T("nvuxa"), _T("nnva"), _T("nnvula"), _T("nnvuxa"), _T("xnva"), _T("xnvula"), _T("xnvuxa"), NULL } },
    { _T("んヴぃ"), { _T("nvi"), _T("nvyi"), _T("nvuli"), _T("nvuxi"), _T("nvulyi"), _T("nvuxyi"), _T("nnvi"), _T("nnvyi"), _T("nnvuli"), _T("nnvuxi"), _T("nnvulyi"), _T("nnvuxyi"), _T("xnvi"), _T("xnvyi"), _T("xnvuli"), _T("xnvuxi"), _T("xnvulyi"), _T("xnvuxyi"), NULL } },
    { _T("んヴ"), { _T("nvu"), _T("nnvu"), _T("xnvu"), NULL } },
    { _T("んヴぇ"), { _T("nve"), _T("nvye"), _T("nvule"), _T("nvuxe"), _T("nvulye"), _T("nvuxye"), _T("nnve"), _T("nnvye"), _T("nnvule"), _T("nnvuxe"), _T("nnvulye"), _T("nnvuxye"), _T("xnve"), _T("xnvye"), _T("xnvule"), _T("xnvuxe"), _T("xnvulye"), _T("xnvuxye"), NULL } },
    { _T("んヴぉ"), { _T("nvo"), _T("nvulo"), _T("nvuxo"), _T("nnvo"), _T("nnvulo"), _T("nnvuxo"), _T("xnvo"), _T("xnvulo"), _T("xnvuxo"), NULL } },
    { _T("んヴゃ"), { _T("nvya"), _T("nvulya"), _T("nvuxya"), _T("nnvya"), _T("nnvulya"), _T("nnvuxya"), _T("xnvya"), _T("xnvulya"), _T("xnvuxya"), NULL } },
    { _T("んヴゅ"), { _T("nvyu"), _T("nvulyu"), _T("nvuxyu"), _T("nnvyu"), _T("nnvulyu"), _T("nnvuxyu"), _T("xnvyu"), _T("xnvulyu"), _T("xnvuxyu"), NULL } },
    { _T("んヴょ"), { _T("nvyo"), _T("nvulyo"), _T("nvuxyo"), _T("nnvyo"), _T("nnvulyo"), _T("nnvuxyo"), _T("xnvyo"), _T("xnvulyo"), _T("xnvuxyo"), NULL } },
    { _T("んゐ"), { _T("nwyi"), _T("nnwyi"), _T("xnwyi"), NULL } },
    { _T("んゑ"), { _T("nwye"), _T("nnwye"), _T("xnwye"), NULL } },
    { _T("ん、"), { _T("n,"), _T("nn,"), _T("xn,"), NULL } },
    { _T("っか"), { _T("kka"), _T("cca"), _T("ltuka"), _T("xtuka"), _T("ltsuka"), _T("xtsuka"), _T("ltuca"), _T("xtuca"), _T("ltsuca"), _T("xtsuca"), NULL } },
    { _T("っき"), { _T("kki"), _T("ltuki"), _T("xtuki"), _T("ltsuki"), _T("xtsuki"), NULL } },
    { _T("っく"), { _T("kku"), _T("ccu"), _T("ltuku"), _T("xtuku"), _T("ltsuku"), _T("xtsuku"), _T("ltucu"), _T("xtucu"), _T("ltsucu"), _T("xtsucu"), NULL } },
    { _T("っけ"), { _T("kke"), _T("ltuke"), _T("xtuke"), _T("ltsuke"), _T("xtsuke"), NULL } },
    { _T("っこ"), { _T("kko"), _T("cco"), _T("ltuko"), _T("xtuko"), _T("ltsuko"), _T("xtsuko"), _T("ltuco"), _T("xtuco"), _T("ltsuco"), _T("xtsuco"), NULL } },
    { _T("っさ"), { _T("ssa"), _T("ltusa"), _T("xtusa"), _T("ltsusa"), _T("xtsusa"), NULL } },
    { _T("っし"), { _T("ssi"), _T("cci"), _T("sshi"), _T("ltusi"), _T("xtsusi"), _T("ltsusi"), _T("xtsusi"), _T("ltuci"), _T("xtuci"), _T("ltsuci"), _T("xtsuci"), _T("ltushi"), _T("xtushi"), _T("ltsushi"), _T("xtsushi"), NULL } },
    { _T("っす"), { _T("ssu"), _T("ltusu"), _T("xtusu"), _T("ltsusu"), _T("xtsusu"), NULL } },
    { _T("っせ"), { _T("sse"), _T("cce"), _T("ltuse"), _T("xtuse"), _T("ltsuse"), _T("xtsuse"), _T("ltuce"), _T("xtuce"), _T("ltsuce"), _T("xtsuce"), NULL } },
    { _T("っそ"), { _T("sso"), _T("ltuso"), _T("xtuso"), _T("ltsuso"), _T("xtsuso"), NULL } },
    { _T("った"), { _T("tta"), _T("ltuta"), _T("xtuta"), _T("ltsuta"), _T("xtsuta"), NULL } },
    { _T("っち"), { _T("tti"), _T("cchi"), _T("ltuti"), _T("xtuti"), _T("ltsuti"), _T("xtsuti"), _T("ltuchi"), _T("xtuchi"), _T("ltsuchi"), _T("xtsuchi"), NULL } },
    { _T("っつ"), { _T("ttu"), _T("ttsu"), _T("ltutu"), _T("xtutu"), _T("ltsutu"), _T("xtsutu"), _T("ltutsu"), _T("xtutsu"), _T("ltsutsu"), _T("xtsutsu"), NULL } },
    { _T("って"), { _T("tte"), _T("ltute"), _T("xtute"), _T("ltsute"), _T("xtsute"), NULL } },
    { _T("っと"), { _T("tto"), _T("ltuto"), _T("xtuto"), _T("ltsuto"), _T("xtsuto"), NULL } },
    { _T("っな"), { _T("ltuna"), _T("xtuna"), _T("ltsuna"), _T("xtsuna"), NULL } },
    { _T("っに"), { _T("ltuni"), _T("xtuni"), _T("ltsuni"), _T("xtsuni"), NULL } },
    { _T("っぬ"), { _T("ltunu"), _T("xtunu"), _T("ltsunu"), _T("xtsunu"), NULL } },
    { _T("っね"), { _T("ltune"), _T("xtune"), _T("ltsune"), _T("xtsune"), NULL } },
    { _T("っの"), { _T("ltuno"), _T("xtuno"), _T("ltsuno"), _T("xtsuno"), NULL } },
    { _T("っは"), { _T("hha"), _T("ltuha"), _T("xtuha"), _T("ltsuha"), _T("xtsuha"), NULL } },
    { _T("っひ"), { _T("hhi"), _T("ltuhi"), _T("xtuhi"), _T("ltsuhi"), _T("xtsuhi"), NULL } },
    { _T("っふ"), { _T("ffu"), _T("hhu"), _T("ltufu"), _T("xtufu"), _T("ltsufu"), _T("xtsufu"), _T("ltuhu"), _T("xtuhu"), _T("ltsuhu"), _T("xtsuhu"), NULL } },
    { _T("っへ"), { _T("hhe"), _T("ltuhe"), _T("xtuhe"), _T("ltsuhe"), _T("xtsuhe"), NULL } },
    { _T("っほ"), { _T("hho"), _T("ltuho"), _T("xtuho"), _T("ltsuho"), _T("xtsuho"), NULL } },
    { _T("っま"), { _T("mma"), _T("ltuma"), _T("xtuma"), _T("ltsuma"), _T("xtsuma"), NULL } },
    { _T("っみ"), { _T("mmi"), _T("ltumi"), _T("xtumi"), _T("ltsumi"), _T("xtsumi"), NULL } },
    { _T("っむ"), { _T("mmu"), _T("ltumu"), _T("xtumu"), _T("ltsumu"), _T("xtsumu"), NULL } },
    { _T("っめ"), { _T("mme"), _T("ltume"), _T("xtume"), _T("ltsume"), _T("xtsume"), NULL } },
    { _T("っも"), { _T("mmo"), _T("ltumo"), _T("xtumo"), _T("ltsumo"), _T("xtsumo"), NULL } },
    { _T("っや"), { _T("yya"), _T("ltuya"), _T("xtuya"), _T("ltsuya"), _T("xtsuya"), NULL } },
    { _T("っゆ"), { _T("yyu"), _T("ltuyu"), _T("xtuyu"), _T("ltsuyu"), _T("xtsuyu"), NULL } },
    { _T("っよ"), { _T("yyo"), _T("ltuyo"), _T("xtuyo"), _T("ltsuyo"), _T("xtsuyo"), NULL } },
    { _T("っら"), { _T("rra"), _T("ltura"), _T("xtura"), _T("ltsura"), _T("xtsura"), NULL } },
    { _T("っり"), { _T("rri"), _T("lturi"), _T("xturi"), _T("ltsuri"), _T("xtsuri"), NULL } },
    { _T("っる"), { _T("rru"), _T("lturu"), _T("xturu"), _T("ltsuru"), _T("xtsuru"), NULL } },
    { _T("っれ"), { _T("rre"), _T("lture"), _T("xture"), _T("ltsure"), _T("xtsure"), NULL } },
    { _T("っろ"), { _T("rro"), _T("lturo"), _T("xturo"), _T("ltsuro"), _T("xtsuro"), NULL } },
    { _T("っわ"), { _T("wwa"), _T("ltuwa"), _T("xtuwa"), _T("ltsuwa"), _T("xtsuwa"), NULL } },
    { _T("っを"), { _T("wwo"), _T("ltuwo"), _T("xtuwo"), _T("ltsuwo"), _T("xtsuwo"), NULL } },
    { _T("っが"), { _T("gga"), _T("ltuga"), _T("xtuga"), _T("ltsuga"), _T("xtsuga"), NULL } },
    { _T("っぎ"), { _T("ggi"), _T("ltugi"), _T("xtugi"), _T("ltsugi"), _T("xtsugi"), NULL } },
    { _T("っぐ"), { _T("ggu"), _T("ltugu"), _T("xtugu"), _T("ltsugu"), _T("xtsugu"), NULL } },
    { _T("っげ"), { _T("gge"), _T("ltuge"), _T("xtuge"), _T("ltsuge"), _T("xtsuge"), NULL } },
    { _T("っご"), { _T("ggo"), _T("ltugo"), _T("xtugo"), _T("ltsugo"), _T("xtsugo"), NULL } },
    { _T("っざ"), { _T("zza"), _T("ltuza"), _T("xtuza"), _T("ltsuza"), _T("xtsuza"), NULL } },
    { _T("っじ"), { _T("jji"), _T("zzi"), _T("ltuji"), _T("xtuji"), _T("ltsuji"), _T("xtsuji"), _T("ltuzi"), _T("xtuzi"), _T("ltsuzi"), _T("xtsuzi"), NULL } },
    { _T("っず"), { _T("zzu"), _T("ltuzu"), _T("xtuzu"), _T("ltsuzu"), _T("xtsuzu"), NULL } },
    { _T("っぜ"), { _T("zze"), _T("ltuze"), _T("xtuze"), _T("ltsuze"), _T("xtsuze"), NULL } },
    { _T("っぞ"), { _T("zzo"), _T("ltuzo"), _T("xtuzo"), _T("ltsuzo"), _T("xtsuzo"), NULL } },
    { _T("っだ"), { _T("dda"), _T("ltuda"), _T("xtuda"), _T("ltsuda"), _T("xtsuda"), NULL } },
    { _T("っぢ"), { _T("ddi"), _T("ltudi"), _T("xtudi"), _T("ltsudi"), _T("xtsudi"), NULL } },
    { _T("っづ"), { _T("ddu"), _T("ltudu"), _T("xtudu"), _T("ltsudu"), _T("xtsudu"), NULL } },
    { _T("っで"), { _T("dde"), _T("ltude"), _T("xtude"), _T("ltsude"), _T("xtsude"), NULL } },
    { _T("っど"), { _T("ddo"), _T("ltudo"), _T("xtudo"), _T("ltsudo"), _T("xtsudo"), NULL } },
    { _T("っば"), { _T("bba"), _T("ltuba"), _T("xtuba"), _T("ltsuba"), _T("xtsuba"), NULL } },
    { _T("っび"), { _T("bbi"), _T("ltubi"), _T("xtubi"), _T("ltsubi"), _T("xtsubi"), NULL } },
    { _T("っぶ"), { _T("bbu"), _T("ltubu"), _T("xtubu"), _T("ltsubu"), _T("xtsubu"), NULL } },
    { _T("っべ"), { _T("bbe"), _T("ltube"), _T("xtube"), _T("ltsube"), _T("xtsube"), NULL } },
    { _T("っぼ"), { _T("bbo"), _T("ltubo"), _T("xtubo"), _T("ltsubo"), _T("xtsubo"), NULL } },
    { _T("っぱ"), { _T("ppa"), _T("ltupa"), _T("xtupa"), _T("ltsupa"), _T("xtsupa"), NULL } },
    { _T("っぴ"), { _T("ppi"), _T("ltupi"), _T("xtupi"), _T("ltsupi"), _T("xtsupi"), NULL } },
    { _T("っぷ"), { _T("ppu"), _T("ltupu"), _T("xtupu"), _T("ltsupu"), _T("xtsupu"), NULL } },
    { _T("っぺ"), { _T("ppe"), _T("ltupe"), _T("xtupe"), _T("ltsupe"), _T("xtsupe"), NULL } },
    { _T("っぽ"), { _T("ppo"), _T("ltupo"), _T("xtupo"), _T("ltsupo"), _T("xtsupo"), NULL } },
    { _T("っきゃ"), { _T("kkya"), _T("kkilya"), _T("kkixya"), _T("ltukya"), _T("ltukilya"), _T("ltukixya"), _T("xtukya"), _T("xtukilya"), _T("xtukixya"), _T("ltsukya"), _T("ltsukilya"), _T("ltsukixya"), _T("xtsukya"), _T("xtsukilya"), _T("xtsukixya"), NULL } },
    { _T("っきぃ"), { _T("kkyi"), _T("kkili"), _T("kkilyi"), _T("kkixi"), _T("kkixyi"), _T("ltukyi"), _T("ltukili"), _T("ltukilyi"), _T("ltukixi"), _T("ltukixyi"), _T("xtukyi"), _T("xtukili"), _T("xtukilyi"), _T("xtukixi"), _T("xtukixyi"), _T("ltsukyi"), _T("ltsukili"), _T("ltsukilyi"), _T("ltsukixi"), _T("ltsukixyi"), _T("ltsukyi"), _T("xtsukili"), _T("xtsukilyi"), _T("xtsukixi"), _T("xtsukixyi"), NULL } },
    { _T("っきゅ"), { _T("kkyu"), _T("kkilyu"), _T("kkixyu"), _T("ltukyu"), _T("ltukilyu"), _T("ltukixyu"), _T("xtukyu"), _T("xtukilyu"), _T("xtukixyu"), _T("ltsukyu"), _T("ltsukilyu"), _T("ltsukixyu"), _T("xtsukyu"), _T("xtsukilyu"), _T("xtsukixyu"), NULL } },
    { _T("っきょ"), { _T("kkyo"), _T("kkilyo"), _T("kkixyo"), _T("ltukyo"), _T("xtukyo"), _T("ltsukyo"), _T("xtsukyo"), _T("ltukilyo"), _T("xtukilyo"), _T("ltsukilyo"), _T("xtsukilyo"), _T("ltukixyo"), _T("xtukixyo"), _T("ltsukixyo"), _T("xtsukixyo"), NULL } },
    { _T("っぎゃ"), { _T("ggya"), _T("ggilya"), _T("ggixya"), _T("ltugya"), _T("xtugya"), _T("ltsugya"), _T("xtsugya"), _T("ltugilya"), _T("xtugilya"), _T("ltsugilya"), _T("xtsugilya"), _T("ltugixya"), _T("xtugixya"), _T("ltsugixya"), _T("xtsugixya"), NULL } },
    { _T("っぎぃ"), { _T("ggyi"), _T("ggili"), _T("ggilyi"), _T("ggixi"), _T("ggixyi"), _T("ltugyi"), _T("xtugyi"), _T("ltsugyi"), _T("xtsugyi"), _T("ltugili"), _T("xtugili"), _T("ltsugili"), _T("xtsugili"), _T("ltugilyi"), _T("xtugilyi"), _T("ltsugilyi"), _T("xtsugilyi"), _T("ltugixi"), _T("xtugixi"), _T("ltsugixi"), _T("xtsugixi"), _T("ltugixyi"), _T("xtugixyi"), _T("ltsugixyi"), _T("xtsugixyi"), NULL } },
    { _T("っぎゅ"), { _T("ggyu"), _T("ggilyu"), _T("ggixyu"), _T("ltugyu"), _T("xtugyu"), _T("ltsugyu"), _T("xtsugyu"), _T("ltugilyu"), _T("xtugilyu"), _T("ltsugilyu"), _T("xtsugilyu"), _T("ltugixyu"), _T("xtugixyu"), _T("ltsugixyu"), _T("xtsugixyu"), NULL } },
    { _T("っぎょ"), { _T("ggyo"), _T("ggilyo"), _T("ggixyo"), _T("ltugyo"), _T("xtugyo"), _T("ltsugyo"), _T("xtsugyo"), _T("ltugilyo"), _T("xtugilyo"), _T("ltsugilyo"), _T("xtsugilyo"), _T("ltugixyo"), _T("xtugixyo"), _T("ltsugixyo"), _T("xtsugixyo"), NULL } },
    { _T("っしゃ"), { _T("ssya"), _T("ssha"), _T("ssilya"), _T("ssixya"), _T("sshilya"), _T("sshixya"), _T("ccilya"), _T("ccixya"), _T("ltusya"), _T("xtusya"), _T("ltsusya"), _T("xtsusya"), _T("ltusha"), _T("xtusha"), _T("ltsusha"), _T("xtsusha"), _T("ltusilya"), _T("xtusilya"), _T("ltsusilya"), _T("xtsusilya"), _T("ltusixya"), _T("xtusixya"), _T("ltsusixya"), _T("xtsusixya"), _T("ltushilya"), _T("xtushilya"), _T("ltsushilya"), _T("xtsushilya"), _T("ltushixya"), _T("xtushixya"), _T("ltsushixya"), _T("xtsushixya"), _T("ltucilya"), _T("xtucilya"), _T("ltsucilya"), _T("xtsucilya"), _T("ltucixya"), _T("xtucixya"), _T("ltsucixya"), _T("xtsucixya"), NULL } },
    { _T("っしぃ"), { _T("ssyi"), _T("ssili"), _T("ssixi"), _T("ssilyi"), _T("ssixyi"), _T("sshili"), _T("sshixi"), _T("sshilyi"), _T("sshixyi"), _T("ccili"), _T("ccixi"), _T("ccilyi"), _T("ccixyi"), _T("ltusyi"), _T("xtusyi"), _T("ltsusyi"), _T("xtsusyi"), _T("ltusili"), _T("xtusili"), _T("ltsusili"), _T("xtsusili"), _T("ltusixi"), _T("xtusixi"), _T("ltsusixi"), _T("xtsusixi"), _T("ltusilyi"), _T("xtusilyi"), _T("ltsusilyi"), _T("xtsusilyi"), _T("ltusixyi"), _T("xtusixyi"), _T("ltsusixyi"), _T("xtsusixyi"), _T("ltushili"), _T("xtushili"), _T("ltsushili"), _T("xtsushili"), _T("ltushixi"), _T("xtushixi"), _T("ltsushixi"), _T("xtsushixi"), _T("ltushilyi"), _T("xtushilyi"), _T("ltsushilyi"), _T("xtsushilyi"), _T("ltushixyi"), _T("xtushixyi"), _T("ltsushixyi"), _T("xtsushixyi"), _T("ltucili"), _T("xtucili"), _T("ltsucili"), _T("xtsucili"), _T("ltucixi"), _T("xtucixi"), _T("ltsucixi"), _T("xtsucixi"), _T("ltucilyi"), _T("xtucilyi"), _T("ltsucilyi"), _T("xtsucilyi"), _T("ltucixyi"), _T("xtucixyi"), _T("ltsucixyi"), _T("xtsucixyi"), NULL } },
    { _T("っしゅ"), { _T("ssyu"), _T("sshu"), _T("ssilyu"), _T("ssixyu"), _T("sshilyu"), _T("sshixyu"), _T("ccilyu"), _T("ccixyu"), _T("ltusyu"), _T("xtusyu"), _T("ltsusyu"), _T("xtsusyu"), _T("ltushu"), _T("xtushu"), _T("ltsushu"), _T("xtsushu"), _T("ltusilyu"), _T("xtusilyu"), _T("ltsusilyu"), _T("xtsusilyu"), _T("ltusixyu"), _T("xtusixyu"), _T("ltsusixyu"), _T("xtsusixyu"), _T("ltushilyu"), _T("xtushilyu"), _T("ltsushilyu"), _T("xtsushilyu"), _T("ltushixyu"), _T("xtushixyu"), _T("ltsushixyu"), _T("xtsushixyu"), _T("ltucilyu"), _T("xtucilyu"), _T("ltsucilyu"), _T("xtsucilyu"), _T("ltucixyu"), _T("xtucixyu"), _T("ltsucixyu"), _T("xtsucixyu"), NULL } },
    { _T("っしぇ"), { _T("ssye"), _T("sshe"), _T("ssile"), _T("ssilye"), _T("ssixe"), _T("ssixye"), _T("sshile"), _T("sshilye"), _T("sshixe"), _T("sshixye"), _T("ccile"), _T("ccilye"), _T("ccixe"), _T("ccixye"), _T("ltusye"), _T("xtusye"), _T("ltsusye"), _T("xtsusye"), _T("ltushe"), _T("xtushe"), _T("ltsushe"), _T("xtsushe"), _T("ltusile"), _T("xtusile"), _T("ltsusile"), _T("xtsusile"), _T("ltusilye"), _T("xtusilye"), _T("ltsusilye"), _T("xtsusilye"), _T("ltusixe"), _T("xtusixe"), _T("ltsusixe"), _T("xtsusixe"), _T("ltusixye"), _T("xtusixye"), _T("ltsusixye"), _T("xtsusixye"), _T("ltushile"), _T("xtushile"), _T("ltsushile"), _T("xtsushile"), _T("ltushilye"), _T("xtushilye"), _T("ltsushilye"), _T("xtsushilye"), _T("ltushixe"), _T("xtushixe"), _T("ltsushixe"), _T("xtsushixe"), _T("ltushixye"), _T("xtushixye"), _T("ltsushixye"), _T("xtsushixye"), _T("ltucile"), _T("xtucile"), _T("ltsucile"), _T("xtsucile"), _T("ltucilye"), _T("xtucilye"), _T("ltsucilye"), _T("xtsucilye"), _T("ltucixe"), _T("xtucixe"), _T("ltsucixe"), _T("xtsucixe"), _T("ltucixye"), _T("xtucixye"), _T("ltsucixye"), _T("xtsucixye"), NULL } },
    { _T("っしょ"), { _T("ssyo"), _T("ssho"), _T("ssilyo"), _T("ssixyo"), _T("sshilyo"), _T("sshixyo"), _T("ccilyo"), _T("ccixyo"), _T("ltusyo"), _T("xtusyo"), _T("ltsusyo"), _T("xtsusyo"), _T("ltusho"), _T("xtusho"), _T("ltsusho"), _T("xtsusho"), _T("ltusilyo"), _T("xtusilyo"), _T("ltsusilyo"), _T("xtsusilyo"), _T("ltusixyo"), _T("xtusixyo"), _T("ltsusixyo"), _T("xtsusixyo"), _T("ltushilyo"), _T("xtushilyo"), _T("ltsushilyo"), _T("xtsushilyo"), _T("ltushixyo"), _T("xtushixyo"), _T("ltsushixyo"), _T("xtsushixyo"), _T("ltucilyo"), _T("xtucilyo"), _T("ltsucilyo"), _T("xtsucilyo"), _T("ltucixyo"), _T("xtucixyo"), _T("ltsucixyo"), _T("xtsucixyo"), NULL } },
    { _T("っじゃ"), { _T("jja"), _T("jjya"), _T("zzya"), _T("jjilya"), _T("jjixya"), _T("zzilya"), _T("zzixya"), _T("ltuja"), _T("xtuja"), _T("ltsuja"), _T("xtsuja"), _T("ltujya"), _T("xtujya"), _T("ltsujya"), _T("xtsujya"), _T("ltuzya"), _T("xtuzya"), _T("ltsuzya"), _T("xtsuzya"), _T("ltujilya"), _T("xtujilya"), _T("ltsujilya"), _T("xtsujilya"), _T("ltujixya"), _T("xtujixya"), _T("ltsujixya"), _T("xtsujixya"), _T("ltuzilya"), _T("xtuzilya"), _T("ltsuzilya"), _T("xtsuzilya"), _T("ltuzixya"), _T("xtuzixya"), _T("ltsuzixya"), _T("xtsuzixya"), NULL } },
    { _T("っじぃ"), { _T("jjyi"), _T("zzyi"), _T("jjili"), _T("jjixi"), _T("jjilyi"), _T("jjixyi"), _T("zzili"), _T("zzixi"), _T("zzilyi"), _T("zzixyi"), _T("ltujyi"), _T("xtujyi"), _T("ltsujyi"), _T("xtsujyi"), _T("ltuzyi"), _T("xtuzyi"), _T("ltsuzyi"), _T("xtsuzyi"), _T("ltujili"), _T("xtujili"), _T("ltsujili"), _T("xtsujili"), _T("ltujixi"), _T("xtujixi"), _T("ltsujixi"), _T("xtsujixi"), _T("ltujilyi"), _T("xtujilyi"), _T("ltsujilyi"), _T("xtsujilyi"), _T("ltujixyi"), _T("xtujixyi"), _T("ltsujixyi"), _T("xtsujixyi"), _T("ltuzili"), _T("xtuzili"), _T("ltsuzili"), _T("xtsuzili"), _T("ltuzixi"), _T("xtuzixi"), _T("ltsuzixi"), _T("xtsuzixi"), _T("ltuzilyi"), _T("xtuzilyi"), _T("ltsuzilyi"), _T("xtsuzilyi"), _T("ltuzixyi"), _T("xtuzixyi"), _T("ltsuzixyi"), _T("xtsuzixyi"), NULL } },
    { _T("っじゅ"), { _T("jju"), _T("jjyu"), _T("zzyu"), _T("jjilyu"), _T("jjixyu"), _T("zzilyu"), _T("zzixyu"), _T("ltuju"), _T("xtuju"), _T("ltsuju"), _T("xtsuju"), _T("ltujyu"), _T("xtujyu"), _T("ltsujyu"), _T("xtsujyu"), _T("ltuzyu"), _T("xtuzyu"), _T("ltsuzyu"), _T("xtsuzyu"), _T("ltujilyu"), _T("xtujilyu"), _T("ltsujilyu"), _T("xtsujilyu"), _T("ltujixyu"), _T("xtujixyu"), _T("ltsujixyu"), _T("xtsujixyu"), _T("ltuzilyu"), _T("xtuzilyu"), _T("ltsuzilyu"), _T("xtsuzilyu"), _T("ltuzixyu"), _T("xtuzixyu"), _T("ltsuzixyu"), _T("xtsuzixyu"), NULL } },
    { _T("っじぇ"), { _T("jje"), _T("jjye"), _T("zzye"), _T("jjile"), _T("jjixe"), _T("jjilye"), _T("jjixye"), _T("zzile"), _T("zzixe"), _T("zzilye"), _T("zzixye"), _T("ltuje"), _T("xtuje"), _T("ltsuje"), _T("xtsuje"), _T("ltujye"), _T("xtujye"), _T("ltsujye"), _T("xtsujye"), _T("ltuzye"), _T("xtuzye"), _T("ltsuzye"), _T("xtsuzye"), _T("ltujile"), _T("xtujile"), _T("ltsujile"), _T("xtsujile"), _T("ltujixe"), _T("xtujixe"), _T("ltsujixe"), _T("xtsujixe"), _T("ltujilye"), _T("xtujilye"), _T("ltsujilye"), _T("xtsujilye"), _T("ltujixye"), _T("xtujixye"), _T("ltsujixye"), _T("xtsujixye"), _T("ltuzile"), _T("xtuzile"), _T("ltsuzile"), _T("xtsuzile"), _T("ltuzixe"), _T("xtuzixe"), _T("ltsuzixe"), _T("xtsuzixe"), _T("ltuzilye"), _T("xtuzilye"), _T("ltsuzilye"), _T("xtsuzilye"), _T("ltuzixye"), _T("xtuzixye"), _T("ltsuzixye"), _T("xtsuzixye"), NULL } },
    { _T("っじょ"), { _T("jjo"), _T("jjyo"), _T("zzyo"), _T("jjilyo"), _T("jjixyo"), _T("zzilyo"), _T("zzixyo"), _T("ltujo"), _T("xtujo"), _T("ltsujo"), _T("xtsujo"), _T("ltujyo"), _T("xtujyo"), _T("ltsujyo"), _T("xtsujyo"), _T("ltuzyo"), _T("xtuzyo"), _T("ltsuzyo"), _T("xtsuzyo"), _T("ltujilyo"), _T("xtujilyo"), _T("ltsujilyo"), _T("xtsujilyo"), _T("ltujixyo"), _T("xtujixyo"), _T("ltsujixyo"), _T("xtsujixyo"), _T("ltuzilyo"), _T("xtuzilyo"), _T("ltsuzilyo"), _T("xtsuzilyo"), _T("ltuzixyo"), _T("xtuzixyo"), _T("ltsuzixyo"), _T("xtsuzixyo"), NULL } },
    { _T("っちゃ"), { _T("ttya"), _T("ccha"), _T("ccya"), _T("ttilya"), _T("ttixya"), _T("cchilya"), _T("cchixya"), _T("ltutya"), _T("xtutya"), _T("ltsutya"), _T("xtsutya"), _T("ltucha"), _T("xtucha"), _T("ltsucha"), _T("xtsucha"), _T("ltucya"), _T("xtucya"), _T("ltsucya"), _T("xtsucya"), _T("ltutilya"), _T("xtutilya"), _T("ltsutilya"), _T("xtsutilya"), _T("ltutixya"), _T("xtutixya"), _T("ltsutixya"), _T("xtsutixya"), _T("ltuchilya"), _T("xtuchilya"), _T("ltsuchilya"), _T("xtsuchilya"), _T("ltuchixya"), _T("xtuchixya"), _T("ltsuchixya"), _T("xtsuchixya"), NULL } },
    { _T("っちぃ"), { _T("ttyi"), _T("ccyi"), _T("ttili"), _T("ttixi"), _T("ttilyi"), _T("ttixyi"), _T("cchili"), _T("cchixi"), _T("cchilyi"), _T("cchixyi"), _T("ltutyi"), _T("xtutyi"), _T("ltsutyi"), _T("xtsutyi"), _T("ltucyi"), _T("xtucyi"), _T("ltsucyi"), _T("xtsucyi"), _T("ltutili"), _T("xtutili"), _T("ltsutili"), _T("xtsutili"), _T("ltutixi"), _T("xtutixi"), _T("ltsutixi"), _T("xtsutixi"), _T("ltutilyi"), _T("xtutilyi"), _T("ltsutilyi"), _T("xtsutilyi"), _T("ltutixyi"), _T("xtutixyi"), _T("ltsutixyi"), _T("xtsutixyi"), _T("ltuchili"), _T("xtuchili"), _T("ltsuchili"), _T("xtsuchili"), _T("ltuchixi"), _T("xtuchixi"), _T("ltsuchixi"), _T("xtsuchixi"), _T("ltuchilyi"), _T("xtuchilyi"), _T("ltsuchilyi"), _T("xtsuchilyi"), _T("ltuchixyi"), _T("xtuchixyi"), _T("ltsuchixyi"), _T("xtsuchixyi"), NULL } },
    { _T("っちゅ"), { _T("ttyu"), _T("cchu"), _T("ccyu"), _T("ttilyu"), _T("ttixyu"), _T("cchilyu"), _T("cchixyu"), _T("ltutyu"), _T("xtutyu"), _T("ltsutyu"), _T("xtsutyu"), _T("ltuchu"), _T("xtuchu"), _T("ltsuchu"), _T("xtsuchu"), _T("ltucyu"), _T("xtucyu"), _T("ltsucyu"), _T("xtsucyu"), _T("ltutilyu"), _T("xtutilyu"), _T("ltsutilyu"), _T("xtsutilyu"), _T("ltutixyu"), _T("xtutixyu"), _T("ltsutixyu"), _T("xtsutixyu"), _T("ltuchilyu"), _T("xtuchilyu"), _T("ltsuchilyu"), _T("xtsuchilyu"), _T("ltuchixyu"), _T("xtuchixyu"), _T("ltsuchixyu"), _T("xtsuchixyu"), NULL } },
    { _T("っちぇ"), { _T("ttye"), _T("cche"), _T("ccye"), _T("ttile"), _T("ttixe"), _T("ttilye"), _T("ttixye"), _T("cchile"), _T("cchixe"), _T("cchilye"), _T("cchixye"), _T("ltutye"), _T("xtutye"), _T("ltsutye"), _T("xtsutye"), _T("ltuche"), _T("xtuche"), _T("ltsuche"), _T("xtsuche"), _T("ltucye"), _T("xtucye"), _T("ltsucye"), _T("xtsucye"), _T("ltutile"), _T("xtutile"), _T("ltsutile"), _T("xtsutile"), _T("ltutixe"), _T("xtutixe"), _T("ltsutixe"), _T("xtsutixe"), _T("ltutilye"), _T("xtutilye"), _T("ltsutilye"), _T("xtsutilye"), _T("ltutixye"), _T("xtutixye"), _T("ltsutixye"), _T("xtsutixye"), _T("ltuchile"), _T("xtuchile"), _T("ltsuchile"), _T("xtsuchile"), _T("ltuchixe"), _T("xtuchixe"), _T("ltsuchixe"), _T("xtsuchixe"), _T("ltuchilye"), _T("xtuchilye"), _T("ltsuchilye"), _T("xtsuchilye"), _T("ltuchixye"), _T("xtuchixye"), _T("ltsuchixye"), _T("xtsuchixye"), NULL } },
    { _T("っちょ"), { _T("ttyo"), _T("ccho"), _T("ccyo"), _T("ttilyo"), _T("ttixyo"), _T("cchilyo"), _T("cchixyo"), _T("ltutyo"), _T("xtutyo"), _T("ltsutyo"), _T("xtsutyo"), _T("ltucho"), _T("xtucho"), _T("ltsucho"), _T("xtsucho"), _T("ltucyo"), _T("xtucyo"), _T("ltsucyo"), _T("xtsucyo"), _T("ltutilyo"), _T("xtutilyo"), _T("ltsutilyo"), _T("xtsutilyo"), _T("ltutixyo"), _T("xtutixyo"), _T("ltsutixyo"), _T("xtsutixyo"), _T("ltuchilyo"), _T("xtuchilyo"), _T("ltsuchilyo"), _T("xtsuchilyo"), _T("ltuchixyo"), _T("xtuchixyo"), _T("ltsuchixyo"), _T("xtsuchixyo"), NULL } },
    { _T("っぢゃ"), { _T("ddya"), _T("ddilya"), _T("ddixya"), _T("ltudya"), _T("xtudya"), _T("ltsudya"), _T("xtsudya"), _T("ltudilya"), _T("xtudilya"), _T("ltsudilya"), _T("xtsudilya"), _T("ltudixya"), _T("xtudixya"), _T("ltsudixya"), _T("xtsudixya"), NULL } },
    { _T("っぢぃ"), { _T("ddyi"), _T("ddilyi"), _T("ddixyi"), _T("ltudyi"), _T("xtudyi"), _T("ltsudyi"), _T("xtsudyi"), _T("ltudilyi"), _T("xtudilyi"), _T("ltsudilyi"), _T("xtsudilyi"), _T("ltudixyi"), _T("xtudixyi"), _T("ltsudixyi"), _T("xtsudixyi"), NULL } },
    { _T("っぢゅ"), { _T("ddyu"), _T("ddilyu"), _T("ddixyu"), _T("ltudyu"), _T("xtudyu"), _T("ltsudyu"), _T("xtsudyu"), _T("ltudilyu"), _T("xtudilyu"), _T("ltsudilyu"), _T("xtsudilyu"), _T("ltudixyu"), _T("xtudixyu"), _T("ltsudixyu"), _T("xtsudixyu"), NULL } },
    { _T("っぢぇ"), { _T("ddye"), _T("ddile"), _T("ddixe"), _T("ddilye"), _T("ddixye"), _T("ltudye"), _T("xtudye"), _T("ltsudye"), _T("xtsudye"), _T("ltudile"), _T("xtudile"), _T("ltsudile"), _T("xtsudile"), _T("ltudixe"), _T("xtudixe"), _T("ltsudixe"), _T("xtsudixe"), _T("ltudilye"), _T("xtudilye"), _T("ltsudilye"), _T("xtsudilye"), _T("ltudixye"), _T("xtudixye"), _T("ltsudixye"), _T("xtsudixye"), NULL } },
    { _T("っぢょ"), { _T("ddyo"), _T("ddilyo"), _T("ddixyo"), _T("ltudyo"), _T("xtudyo"), _T("ltsudyo"), _T("xtsudyo"), _T("ltudilyo"), _T("xtudilyo"), _T("ltsudilyo"), _T("xtsudilyo"), _T("ltudixyo"), _T("xtudixyo"), _T("ltsudixyo"), _T("xtsudixyo"), NULL } },
    { _T("っつぁ"), { _T("ttsa"), _T("ttula"), _T("ttuxa"), _T("ttsula"), _T("ttsuxa"), _T("ltutsa"), _T("xtutsa"), _T("ltsutsa"), _T("xtsutsa"), _T("ltutula"), _T("xtutula"), _T("ltsutula"), _T("xtsutula"), _T("ltutuxa"), _T("xtutuxa"), _T("ltsutuxa"), _T("xtsutuxa"), _T("ltutsula"), _T("xtutsula"), _T("ltsutsula"), _T("xtsutsula"), _T("ltutsuxa"), _T("xtutsuxa"), _T("ltsutsuxa"), _T("xtsutsuxa"), NULL } },
    { _T("っつぃ"), { _T("ttsi"), _T("ttuli"), _T("ttuxi"), _T("ttulyi"), _T("ttuxyi"), _T("ttsuli"), _T("ttsuxi"), _T("ttsulyi"), _T("ttsuxyi"), _T("ltutsi"), _T("xtutsi"), _T("ltsutsi"), _T("xtsutsi"), _T("ltutuli"), _T("xtutuli"), _T("ltsutuli"), _T("xtsutuli"), _T("ltutuxi"), _T("xtutuxi"), _T("ltsutuxi"), _T("xtsutuxi"), _T("ltutulyi"), _T("xtutulyi"), _T("ltsutulyi"), _T("xtsutulyi"), _T("ltutuxyi"), _T("xtutuxyi"), _T("ltsutuxyi"), _T("xtsutuxyi"), _T("ltutsuli"), _T("xtutsuli"), _T("ltsutsuli"), _T("xtsutsuli"), _T("ltutsuxi"), _T("xtutsuxi"), _T("ltsutsuxi"), _T("xtsutsuxi"), _T("ltutsulyi"), _T("xtutsulyi"), _T("ltsutsulyi"), _T("xtsutsulyi"), _T("ltutsuxyi"), _T("xtutsuxyi"), _T("ltsutsuxyi"), _T("xtsutsuxyi"), NULL } },
    { _T("っつぇ"), { _T("ttse"), _T("ttule"), _T("ttuxe"), _T("ttulye"), _T("ttuxye"), _T("ttsule"), _T("ttsuxe"), _T("ttsulye"), _T("ttsuxye"), _T("ltutse"), _T("xtutse"), _T("ltsutse"), _T("xtsutse"), _T("ltutule"), _T("xtutule"), _T("ltsutule"), _T("xtsutule"), _T("ltutuxe"), _T("xtutuxe"), _T("ltsutuxe"), _T("xtsutuxe"), _T("ltutulye"), _T("xtutulye"), _T("ltsutulye"), _T("xtsutulye"), _T("ltutuxye"), _T("xtutuxye"), _T("ltsutuxye"), _T("xtsutuxye"), _T("ltutsule"), _T("xtutsule"), _T("ltsutsule"), _T("xtsutsule"), _T("ltutsuxe"), _T("xtutsuxe"), _T("ltsutsuxe"), _T("xtsutsuxe"), _T("ltutsulye"), _T("xtutsulye"), _T("ltsutsulye"), _T("xtsutsulye"), _T("ltutsuxye"), _T("xtutsuxye"), _T("ltsutsuxye"), _T("xtsutsuxye"), NULL } },
    { _T("っつぉ"), { _T("ttso"), _T("ttulo"), _T("ttuxo"), _T("ttsulo"), _T("ttsuxo"), _T("ltutso"), _T("xtutso"), _T("ltsutso"), _T("xtsutso"), _T("ltutulo"), _T("xtutulo"), _T("ltsutulo"), _T("xtsutulo"), _T("ltutuxo"), _T("xtutuxo"), _T("ltsutuxo"), _T("xtsutuxo"), _T("ltutsulo"), _T("xtutsulo"), _T("ltsutsulo"), _T("xtsutsulo"), _T("ltutsuxo"), _T("xtutsuxo"), _T("ltsutsuxo"), _T("xtsutsuxo"), NULL } },
    { _T("ってゃ"), { _T("ttha"), _T("ttelya"), _T("ttexya"), _T("ltutha"), _T("xtutha"), _T("ltsutha"), _T("xtsutha"), _T("ltutelya"), _T("xtutelya"), _T("ltsutelya"), _T("xtsutelya"), _T("ltutexya"), _T("xtutexya"), _T("ltsutexya"), _T("xtsutexya"), NULL } },
    { _T("ってぃ"), { _T("tthi"), _T("tteli"), _T("ttexi"), _T("ttelyi"), _T("ttexyi"), _T("ltuthi"), _T("xtuthi"), _T("ltsuthi"), _T("xtsuthi"), _T("ltuteli"), _T("xtuteli"), _T("ltsuteli"), _T("xtsuteli"), _T("ltutexi"), _T("xtutexi"), _T("ltsutexi"), _T("xtsutexi"), _T("ltutelyi"), _T("xtutelyi"), _T("ltsutelyi"), _T("xtsutelyi"), _T("ltutexyi"), _T("xtutexyi"), _T("ltsutexyi"), _T("xtsutexyi"), NULL } },
    { _T("ってゅ"), { _T("tthu"), _T("ttelyu"), _T("ttexyu"), _T("ltuthu"), _T("xtuthu"), _T("ltsuthu"), _T("xtsuthu"), _T("ltutelyu"), _T("xtutelyu"), _T("ltsutelyu"), _T("xtsutelyu"), _T("ltutexyu"), _T("xtutexyu"), _T("ltsutexyu"), _T("xtsutexyu"), NULL } },
    { _T("ってぇ"), { _T("tthe"), _T("ttele"), _T("ttexe"), _T("ttelye"), _T("ttexye"), _T("ltuthe"), _T("xtuthe"), _T("ltsuthe"), _T("xtsuthe"), _T("ltutele"), _T("xtutele"), _T("ltsutele"), _T("xtsutele"), _T("ltutexe"), _T("xtutexe"), _T("ltsutexe"), _T("xtsutexe"), _T("ltutelye"), _T("xtutelye"), _T("ltsutelye"), _T("xtsutelye"), _T("ltutexye"), _T("xtutexye"), _T("ltsutexye"), _T("xtsutexye"), NULL } },
    { _T("ってょ"), { _T("ttho"), _T("ttelyo"), _T("ttexyo"), _T("ltutho"), _T("xtutho"), _T("ltsutho"), _T("xtsutho"), _T("ltutelyo"), _T("xtutelyo"), _T("ltsutelyo"), _T("xtsutelyo"), _T("ltutexyo"), _T("xtutexyo"), _T("ltsutexyo"), _T("xtsutexyo"), NULL } },
    { _T("っでゃ"), { _T("ddha"), _T("ddelya"), _T("ddexya"), _T("ltudha"), _T("xtudha"), _T("ltsudha"), _T("xtsudha"), _T("ltudelya"), _T("xtudelya"), _T("ltsudelya"), _T("xtsudelya"), _T("ltudexya"), _T("xtudexya"), _T("ltsudexya"), _T("xtsudexya"), NULL } },
    { _T("っでぃ"), { _T("ddhi"), _T("ddeli"), _T("ddexi"), _T("ddelyi"), _T("ddexyi"), _T("ltudhi"), _T("xtudhi"), _T("ltsudhi"), _T("xtsudhi"), _T("ltudeli"), _T("xtudeli"), _T("ltsudeli"), _T("xtsudeli"), _T("ltudexi"), _T("xtudexi"), _T("ltsudexi"), _T("xtsudexi"), _T("ltudelyi"), _T("xtudelyi"), _T("ltsudelyi"), _T("xtsudelyi"), _T("ltudexyi"), _T("xtudexyi"), _T("ltsudexyi"), _T("xtsudexyi"), NULL } },
    { _T("っでゅ"), { _T("ddhu"), _T("ddelyu"), _T("ddexyu"), _T("ltudhu"), _T("xtudhu"), _T("ltsudhu"), _T("xtsudhu"), _T("ltudelyu"), _T("xtudelyu"), _T("ltsudelyu"), _T("xtsudelyu"), _T("ltudexyu"), _T("xtudexyu"), _T("ltsudexyu"), _T("xtsudexyu"), NULL } },
    { _T("っでぇ"), { _T("ddhe"), _T("ddele"), _T("ddexe"), _T("ddelye"), _T("ddexye"), _T("ltudhe"), _T("xtudhe"), _T("ltsudhe"), _T("xtsudhe"), _T("ltudele"), _T("xtudele"), _T("ltsudele"), _T("xtsudele"), _T("ltudexe"), _T("xtudexe"), _T("ltsudexe"), _T("xtsudexe"), _T("ltudelye"), _T("xtudelye"), _T("ltsudelye"), _T("xtsudelye"), _T("ltudexye"), _T("xtudexye"), _T("ltsudexye"), _T("xtsudexye"), NULL } },
    { _T("っでょ"), { _T("ddho"), _T("ddelyo"), _T("ddexyo"), _T("ltudho"), _T("xtudho"), _T("ltsudho"), _T("xtsudho"), _T("ltudelyo"), _T("xtudelyo"), _T("ltsudelyo"), _T("xtsudelyo"), _T("ltudexyo"), _T("xtudexyo"), _T("ltsudexyo"), _T("xtsudexyo"), NULL } },
    { _T("っぴゃ"), { _T("ppya"), _T("ppilya"), _T("ppixya"), _T("ltupya"), _T("xtupya"), _T("ltsupya"), _T("xtsupya"), _T("ltupilya"), _T("xtupilya"), _T("ltsupilya"), _T("xtsupilya"), _T("ltupixya"), _T("xtupixya"), _T("ltsupixya"), _T("xtsupixya"), NULL } },
    { _T("っぴぃ"), { _T("ppyi"), _T("ppili"), _T("ppixi"), _T("ppilyi"), _T("ppixyi"), _T("ltupyi"), _T("xtupyi"), _T("ltsupyi"), _T("xtsupyi"), _T("ltupili"), _T("xtupili"), _T("ltsupili"), _T("xtsupili"), _T("ltupixi"), _T("xtupixi"), _T("ltsupixi"), _T("xtsupixi"), _T("ltupilyi"), _T("xtupilyi"), _T("ltsupilyi"), _T("xtsupilyi"), _T("ltupixyi"), _T("xtupixyi"), _T("ltsupixyi"), _T("xtsupixyi"), NULL } },
    { _T("っぴゅ"), { _T("ppyu"), _T("ppilyu"), _T("ppixyu"), _T("ltupyu"), _T("xtupyu"), _T("ltsupyu"), _T("xtsupyu"), _T("ltupilyu"), _T("xtupilyu"), _T("ltsupilyu"), _T("xtsupilyu"), _T("ltupixyu"), _T("xtupixyu"), _T("ltsupixyu"), _T("xtsupixyu"), NULL } },
    { _T("っぴぇ"), { _T("ppye"), _T("ppile"), _T("ppixe"), _T("ppilye"), _T("ppixye"), _T("ltupye"), _T("xtupye"), _T("ltsupye"), _T("xtsupye"), _T("ltupile"), _T("xtupile"), _T("ltsupile"), _T("xtsupile"), _T("ltupixe"), _T("xtupixe"), _T("ltsupixe"), _T("xtsupixe"), _T("ltupilye"), _T("xtupilye"), _T("ltsupilye"), _T("xtsupilye"), _T("ltupixye"), _T("xtupixye"), _T("ltsupixye"), _T("xtsupixye"), NULL } },
    { _T("っぴょ"), { _T("ppyo"), _T("ppilyo"), _T("ppixyo"), _T("ltupyo"), _T("xtupyo"), _T("ltsupyo"), _T("xtsupyo"), _T("ltupilyo"), _T("xtupilyo"), _T("ltsupilyo"), _T("xtsupilyo"), _T("ltupixyo"), _T("xtupixyo"), _T("ltsupixyo"), _T("xtsupixyo"), NULL } },
    { _T("っひゃ"), { _T("hhya"), _T("hhilya"), _T("hhixya"), _T("ltuhya"), _T("xtuhya"), _T("ltsuhya"), _T("xtsuhya"), _T("ltuhilya"), _T("xtuhilya"), _T("ltsuhilya"), _T("xtsuhilya"), _T("ltuhixya"), _T("xtuhixya"), _T("ltsuhixya"), _T("xtsuhixya"), NULL } },
    { _T("っひぃ"), { _T("hhyi"), _T("hhili"), _T("hhixi"), _T("hhilyi"), _T("hhixyi"), _T("ltuhyi"), _T("xtuhyi"), _T("ltsuhyi"), _T("xtsuhyi"), _T("ltuhili"), _T("xtuhili"), _T("ltsuhili"), _T("xtsuhili"), _T("ltuhixi"), _T("xtuhixi"), _T("ltsuhixi"), _T("xtsuhixi"), _T("ltuhilyi"), _T("xtuhilyi"), _T("ltsuhilyi"), _T("xtsuhilyi"), _T("ltuhixyi"), _T("xtuhixyi"), _T("ltsuhixyi"), _T("xtsuhixyi"), NULL } },
    { _T("っひゅ"), { _T("hhyu"), _T("hhilyu"), _T("hhixyu"), _T("ltuhyu"), _T("xtuhyu"), _T("ltsuhyu"), _T("xtsuhyu"), _T("ltuhilyu"), _T("xtuhilyu"), _T("ltsuhilyu"), _T("xtsuhilyu"), _T("ltuhixyu"), _T("xtuhixyu"), _T("ltsuhixyu"), _T("xtsuhixyu"), NULL } },
    { _T("っひぇ"), { _T("hhye"), _T("hhile"), _T("hhixe"), _T("hhilye"), _T("hhixye"), _T("ltuhye"), _T("xtuhye"), _T("ltsuhye"), _T("xtsuhye"), _T("ltuhile"), _T("xtuhile"), _T("ltsuhile"), _T("xtsuhile"), _T("ltuhixe"), _T("xtuhixe"), _T("ltsuhixe"), _T("xtsuhixe"), _T("ltuhilye"), _T("xtuhilye"), _T("ltsuhilye"), _T("xtsuhilye"), _T("ltuhixye"), _T("xtuhixye"), _T("ltsuhixye"), _T("xtsuhixye"), NULL } },
    { _T("っひょ"), { _T("hhyo"), _T("hhilyo"), _T("hhixyo"), _T("ltuhyo"), _T("xtuhyo"), _T("ltsuhyo"), _T("xtsuhyo"), _T("ltuhilyo"), _T("xtuhilyo"), _T("ltsuhilyo"), _T("xtsuhilyo"), _T("ltuhixyo"), _T("xtuhixyo"), _T("ltsuhixyo"), _T("xtsuhixyo"), NULL } },
    { _T("っびゃ"), { _T("bbya"), _T("bbilya"), _T("bbixya"), _T("ltubya"), _T("xtubya"), _T("ltsubya"), _T("xtsubya"), _T("ltubilya"), _T("xtubilya"), _T("ltsubilya"), _T("xtsubilya"), _T("ltubixya"), _T("xtubixya"), _T("ltsubixya"), _T("xtsubixya"), NULL } },
    { _T("っびぃ"), { _T("bbyi"), _T("bbili"), _T("bbixi"), _T("bbilyi"), _T("bbixyi"), _T("ltubyi"), _T("xtubyi"), _T("ltsubyi"), _T("xtsubyi"), _T("ltubili"), _T("xtubili"), _T("ltsubili"), _T("xtsubili"), _T("ltubixi"), _T("xtubixi"), _T("ltsubixi"), _T("xtsubixi"), _T("ltubilyi"), _T("xtubilyi"), _T("ltsubilyi"), _T("xtsubilyi"), _T("ltubixyi"), _T("xtubixyi"), _T("ltsubixyi"), _T("xtsubixyi"), NULL } },
    { _T("っびゅ"), { _T("bbyu"), _T("bbilyu"), _T("bbixyu"), _T("ltubyu"), _T("xtubyu"), _T("ltsubyu"), _T("xtsubyu"), _T("ltubilyu"), _T("xtubilyu"), _T("ltsubilyu"), _T("xtsubilyu"), _T("ltubixyu"), _T("xtubixyu"), _T("ltsubixyu"), _T("xtsubixyu"), NULL } },
    { _T("っびぇ"), { _T("bbye"), _T("bbile"), _T("bbixe"), _T("bbilye"), _T("bbixye"), _T("ltubye"), _T("xtubye"), _T("ltsubye"), _T("xtsubye"), _T("ltubile"), _T("xtubile"), _T("ltsubile"), _T("xtsubile"), _T("ltubixe"), _T("xtubixe"), _T("ltsubixe"), _T("xtsubixe"), _T("ltubilye"), _T("xtubilye"), _T("ltsubilye"), _T("xtsubilye"), _T("ltubixye"), _T("xtubixye"), _T("ltsubixye"), _T("xtsubixye"), NULL } },
    { _T("っびょ"), { _T("bbyo"), _T("bbilyo"), _T("bbixyo"), _T("ltubyo"), _T("xtubyo"), _T("ltsubyo"), _T("xtsubyo"), _T("ltubilyo"), _T("xtubilyo"), _T("ltsubilyo"), _T("xtsubilyo"), _T("ltubixyo"), _T("xtubixyo"), _T("ltsubixyo"), _T("xtsubixyo"), NULL } },
    { _T("っふぁ"), { _T("ffa"), _T("ffula"), _T("ffuxa"), _T("hhula"), _T("hhuxa"), _T("ltufa"), _T("xtufa"), _T("ltsufa"), _T("xtsufa"), _T("ltufula"), _T("xtufula"), _T("ltsufula"), _T("xtsufula"), _T("ltufuxa"), _T("xtufuxa"), _T("ltsufuxa"), _T("xtsufuxa"), _T("ltuhula"), _T("xtuhula"), _T("ltsuhula"), _T("xtsuhula"), _T("ltuhuxa"), _T("xtuhuxa"), _T("ltsuhuxa"), _T("xtsuhuxa"), NULL } },
    { _T("っふぃ"), { _T("ffi"), _T("ffyi"), _T("ffuli"), _T("ffuxi"), _T("ffulyi"), _T("ffuxyi"), _T("hhuli"), _T("hhuxi"), _T("hhulyi"), _T("hhuxyi"), _T("ltufi"), _T("xtufi"), _T("ltsufi"), _T("xtsufi"), _T("ltufyi"), _T("xtufyi"), _T("ltsufyi"), _T("xtsufyi"), _T("ltufuli"), _T("xtufuli"), _T("ltsufuli"), _T("xtsufuli"), _T("ltufuxi"), _T("xtufuxi"), _T("ltsufuxi"), _T("xtsufuxi"), _T("ltufulyi"), _T("xtufulyi"), _T("ltsufulyi"), _T("xtsufulyi"), _T("ltufuxyi"), _T("xtufuxyi"), _T("ltsufuxyi"), _T("xtsufuxyi"), _T("ltuhuli"), _T("xtuhuli"), _T("ltsuhuli"), _T("xtsuhuli"), _T("ltuhuxi"), _T("xtuhuxi"), _T("ltsuhuxi"), _T("xtsuhuxi"), _T("ltuhulyi"), _T("xtuhulyi"), _T("ltsuhulyi"), _T("xtsuhulyi"), _T("ltuhuxyi"), _T("xtuhuxyi"), _T("ltsuhuxyi"), _T("xtsuhuxyi"), NULL } },
    { _T("っふぇ"), { _T("ffe"), _T("ffye"), _T("ffule"), _T("ffuxe"), _T("ffulye"), _T("ffuxye"), _T("hhule"), _T("hhuxe"), _T("hhulye"), _T("hhuxye"), _T("ltufe"), _T("xtufe"), _T("ltsufe"), _T("xtsufe"), _T("ltufye"), _T("xtufye"), _T("ltsufye"), _T("xtsufye"), _T("ltufule"), _T("xtufule"), _T("ltsufule"), _T("xtsufule"), _T("ltufuxe"), _T("xtufuxe"), _T("ltsufuxe"), _T("xtsufuxe"), _T("ltufulye"), _T("xtufulye"), _T("ltsufulye"), _T("xtsufulye"), _T("ltufuxye"), _T("xtufuxye"), _T("ltsufuxye"), _T("xtsufuxye"), _T("ltuhule"), _T("xtuhule"), _T("ltsuhule"), _T("xtsuhule"), _T("ltuhuxe"), _T("xtuhuxe"), _T("ltsuhuxe"), _T("xtsuhuxe"), _T("ltuhulye"), _T("xtuhulye"), _T("ltsuhulye"), _T("xtsuhulye"), _T("ltuhuxye"), _T("xtuhuxye"), _T("ltsuhuxye"), _T("xtsuhuxye"), NULL } },
    { _T("っふぉ"), { _T("ffo"), _T("ffulo"), _T("ffuxo"), _T("hhulo"), _T("hhuxo"), _T("ltufo"), _T("xtufo"), _T("ltsufo"), _T("xtsufo"), _T("ltufulo"), _T("xtufulo"), _T("ltsufulo"), _T("xtsufulo"), _T("ltufuxo"), _T("xtufuxo"), _T("ltsufuxo"), _T("xtsufuxo"), _T("ltuhulo"), _T("xtuhulo"), _T("ltsuhulo"), _T("xtsuhulo"), _T("ltuhuxo"), _T("xtuhuxo"), _T("ltsuhuxo"), _T("xtsuhuxo"), NULL } },
    { _T("っみゃ"), { _T("mmya"), _T("mmilya"), _T("mmixya"), _T("ltumya"), _T("xtumya"), _T("ltsumya"), _T("xtsumya"), _T("ltumilya"), _T("xtumilya"), _T("ltsumilya"), _T("xtsumilya"), _T("ltumixya"), _T("xtumixya"), _T("ltsumixya"), _T("xtsumixya"), NULL } },
    { _T("っみぃ"), { _T("mmyi"), _T("mmili"), _T("mmixi"), _T("mmilyi"), _T("mmixyi"), _T("ltumyi"), _T("xtumyi"), _T("ltsumyi"), _T("xtsumyi"), _T("ltumili"), _T("xtumili"), _T("ltsumili"), _T("xtsumili"), _T("ltumixi"), _T("xtumixi"), _T("ltsumixi"), _T("xtsumixi"), _T("ltumilyi"), _T("xtumilyi"), _T("ltsumilyi"), _T("xtsumilyi"), _T("ltumixyi"), _T("xtumixyi"), _T("ltsumixyi"), _T("xtsumixyi"), NULL } },
    { _T("っみゅ"), { _T("mmyu"), _T("mmilyu"), _T("mmixyu"), _T("ltumyu"), _T("xtumyu"), _T("ltsumyu"), _T("xtsumyu"), _T("ltumilyu"), _T("xtumilyu"), _T("ltsumilyu"), _T("xtsumilyu"), _T("ltumixyu"), _T("xtumixyu"), _T("ltsumixyu"), _T("xtsumixyu"), NULL } },
    { _T("っみぇ"), { _T("mmye"), _T("mmile"), _T("mmixe"), _T("mmilye"), _T("mmixye"), _T("ltumye"), _T("xtumye"), _T("ltsumye"), _T("xtsumye"), _T("ltumile"), _T("xtumile"), _T("ltsumile"), _T("xtsumile"), _T("ltumixe"), _T("xtumixe"), _T("ltsumixe"), _T("xtsumixe"), _T("ltumilye"), _T("xtumilye"), _T("ltsumilye"), _T("xtsumilye"), _T("ltumixye"), _T("xtumixye"), _T("ltsumixye"), _T("xtsumixye"), NULL } },
    { _T("っみょ"), { _T("mmyo"), _T("mmilyo"), _T("mmixyo"), _T("ltumyo"), _T("xtumyo"), _T("ltsumyo"), _T("xtsumyo"), _T("ltumilyo"), _T("xtumilyo"), _T("ltsumilyo"), _T("xtsumilyo"), _T("ltumixyo"), _T("xtumixyo"), _T("ltsumixyo"), _T("xtsumixyo"), NULL } },
    { _T("っりゃ"), { _T("rrya"), _T("rrilya"), _T("rrixya"), _T("lturya"), _T("xturya"), _T("ltsurya"), _T("xtsurya"), _T("lturilya"), _T("xturilya"), _T("ltsurilya"), _T("xtsurilya"), _T("lturixya"), _T("xturixya"), _T("ltsurixya"), _T("xtsurixya"), NULL } },
    { _T("っりぃ"), { _T("rryi"), _T("rrili"), _T("rrixi"), _T("rrilyi"), _T("rrixyi"), _T("lturyi"), _T("xturyi"), _T("ltsuryi"), _T("xtsuryi"), _T("lturili"), _T("xturili"), _T("ltsurili"), _T("xtsurili"), _T("lturixi"), _T("xturixi"), _T("ltsurixi"), _T("xtsurixi"), _T("lturilyi"), _T("xturilyi"), _T("ltsurilyi"), _T("xtsurilyi"), _T("lturixyi"), _T("xturixyi"), _T("ltsurixyi"), _T("xtsurixyi"), NULL } },
    { _T("っりゅ"), { _T("rryu"), _T("rrilyu"), _T("rrixyu"), _T("lturyu"), _T("xturyu"), _T("ltsuryu"), _T("xtsuryu"), _T("lturilyu"), _T("xturilyu"), _T("ltsurilyu"), _T("xtsurilyu"), _T("lturixyu"), _T("xturixyu"), _T("ltsurixyu"), _T("xtsurixyu"), NULL } },
    { _T("っりぇ"), { _T("rrye"), _T("rrile"), _T("rrixe"), _T("rrilye"), _T("rrixye"), _T("lturye"), _T("xturye"), _T("ltsurye"), _T("xtsurye"), _T("lturile"), _T("xturile"), _T("ltsurile"), _T("xtsurile"), _T("lturixe"), _T("xturixe"), _T("ltsurixe"), _T("xtsurixe"), _T("lturilye"), _T("xturilye"), _T("ltsurilye"), _T("xtsurilye"), _T("lturixye"), _T("xturixye"), _T("ltsurixye"), _T("xtsurixye"), NULL } },
    { _T("っりょ"), { _T("rryo"), _T("rrilyo"), _T("rrixyo"), _T("lturyo"), _T("xturyo"), _T("ltsuryo"), _T("xtsuryo"), _T("lturilyo"), _T("xturilyo"), _T("ltsurilyo"), _T("xtsurilyo"), _T("lturixyo"), _T("xturixyo"), _T("ltsurixyo"), _T("xtsurixyo"), NULL } },
    { _T("ー"), { _T("-"), NULL } },
    { _T("、"), { _T(","), NULL } },
    { _T("。"), { _T("."), NULL } },
    { _T("0"), { _T("0"), NULL } },
    { _T("1"), { _T("1"), NULL } },
    { _T("2"), { _T("2"), NULL } },
    { _T("3"), { _T("3"), NULL } },
    { _T("4"), { _T("4"), NULL } },
    { _T("5"), { _T("5"), NULL } },
    { _T("6"), { _T("6"), NULL } },
    { _T("7"), { _T("7"), NULL } },
    { _T("8"), { _T("8"), NULL } },
    { _T("9"), { _T("9"), NULL } },
    { _T("a"), { _T("a"), NULL } },
    { _T("b"), { _T("b"), NULL } },
    { _T("c"), { _T("c"), NULL } },
    { _T("d"), { _T("d"), NULL } },
    { _T("e"), { _T("e"), NULL } },
    { _T("f"), { _T("f"), NULL } },
    { _T("g"), { _T("g"), NULL } },
    { _T("h"), { _T("h"), NULL } },
    { _T("i"), { _T("i"), NULL } },
    { _T("j"), { _T("j"), NULL } },
    { _T("k"), { _T("k"), NULL } },
    { _T("l"), { _T("l"), NULL } },
    { _T("m"), { _T("m"), NULL } },
    { _T("n"), { _T("n"), NULL } },
    { _T("o"), { _T("o"), NULL } },
    { _T("p"), { _T("p"), NULL } },
    { _T("q"), { _T("q"), NULL } },
    { _T("r"), { _T("r"), NULL } },
    { _T("s"), { _T("s"), NULL } },
    { _T("t"), { _T("t"), NULL } },
    { _T("u"), { _T("u"), NULL } },
    { _T("v"), { _T("v"), NULL } },
    { _T("w"), { _T("w"), NULL } },
    { _T("x"), { _T("x"), NULL } },
    { _T("y"), { _T("y"), NULL } },
    { _T("z"), { _T("z"), NULL } },
    { _T("A"), { _T("A"), NULL } },
    { _T("B"), { _T("B"), NULL } },
    { _T("C"), { _T("C"), NULL } },
    { _T("D"), { _T("D"), NULL } },
    { _T("E"), { _T("E"), NULL } },
    { _T("F"), { _T("F"), NULL } },
    { _T("G"), { _T("G"), NULL } },
    { _T("H"), { _T("H"), NULL } },
    { _T("I"), { _T("I"), NULL } },
    { _T("J"), { _T("J"), NULL } },
    { _T("K"), { _T("K"), NULL } },
    { _T("L"), { _T("L"), NULL } },
    { _T("M"), { _T("M"), NULL } },
    { _T("N"), { _T("N"), NULL } },
    { _T("O"), { _T("O"), NULL } },
    { _T("P"), { _T("P"), NULL } },
    { _T("Q"), { _T("Q"), NULL } },
    { _T("R"), { _T("R"), NULL } },
    { _T("S"), { _T("S"), NULL } },
    { _T("T"), { _T("T"), NULL } },
    { _T("U"), { _T("U"), NULL } },
    { _T("V"), { _T("V"), NULL } },
    { _T("W"), { _T("W"), NULL } },
    { _T("X"), { _T("X"), NULL } },
    { _T("Y"), { _T("Y"), NULL } },
    { _T("Z"), { _T("Z"), NULL } },
    { _T(" "), { _T(" "), NULL } },
    { _T(","), { _T(","), NULL } },
    { _T("."), { _T("."), NULL } },
    { _T("んa"), { _T("nna"), _T("xna"), NULL } },
    { _T("んb"), { _T("nnb"), _T("xnb"), NULL } },
    { _T("んc"), { _T("nnc"), _T("xnc"), NULL } },
    { _T("んd"), { _T("nnd"), _T("xnd"), NULL } },
    { _T("んe"), { _T("nne"), _T("xne"), NULL } },
    { _T("んf"), { _T("nnf"), _T("xnf"), NULL } },
    { _T("んg"), { _T("nng"), _T("xng"), NULL } },
    { _T("んh"), { _T("nnh"), _T("xnh"), NULL } },
    { _T("んi"), { _T("nni"), _T("xni"), NULL } },
    { _T("んj"), { _T("nnj"), _T("xnj"), NULL } },
    { _T("んk"), { _T("nnk"), _T("xnk"), NULL } },
    { _T("んl"), { _T("nnl"), _T("xnl"), NULL } },
    { _T("んm"), { _T("nnm"), _T("xnm"), NULL } },
    { _T("んn"), { _T("nnn"), _T("xnn"), NULL } },
    { _T("んo"), { _T("nno"), _T("xno"), NULL } },
    { _T("んp"), { _T("nnp"), _T("xnp"), NULL } },
    { _T("んq"), { _T("nnq"), _T("xnq"), NULL } },
    { _T("んr"), { _T("nnr"), _T("xnr"), NULL } },
    { _T("んs"), { _T("nns"), _T("xns"), NULL } },
    { _T("んt"), { _T("nnt"), _T("xnt"), NULL } },
    { _T("んu"), { _T("nnu"), _T("xnu"), NULL } },
    { _T("んv"), { _T("nnv"), _T("xnv"), NULL } },
    { _T("んw"), { _T("nnw"), _T("xnw"), NULL } },
    { _T("んx"), { _T("nnx"), _T("xnx"), NULL } },
    { _T("んy"), { _T("nny"), _T("xny"), NULL } },
    { _T("んz"), { _T("nnz"), _T("xnz"), NULL } },
    { _T("んA"), { _T("nnA"), _T("xnA"), NULL } },
    { _T("んB"), { _T("nnB"), _T("xnB"), NULL } },
    { _T("んC"), { _T("nnC"), _T("xnC"), NULL } },
    { _T("んD"), { _T("nnD"), _T("xnD"), NULL } },
    { _T("んE"), { _T("nnE"), _T("xnE"), NULL } },
    { _T("んF"), { _T("nnF"), _T("xnF"), NULL } },
    { _T("んG"), { _T("nnG"), _T("xnG"), NULL } },
    { _T("んH"), { _T("nnH"), _T("xnH"), NULL } },
    { _T("んI"), { _T("nnI"), _T("xnI"), NULL } },
    { _T("んJ"), { _T("nnJ"), _T("xnJ"), NULL } },
    { _T("んK"), { _T("nnK"), _T("xnK"), NULL } },
    { _T("んL"), { _T("nnL"), _T("xnL"), NULL } },
    { _T("んM"), { _T("nnM"), _T("xnM"), NULL } },
    { _T("んN"), { _T("nnN"), _T("xnN"), NULL } },
    { _T("んO"), { _T("nnO"), _T("xnO"), NULL } },
    { _T("んP"), { _T("nnP"), _T("xnP"), NULL } },
    { _T("んQ"), { _T("nnQ"), _T("xnQ"), NULL } },
    { _T("んR"), { _T("nnR"), _T("xnR"), NULL } },
    { _T("んS"), { _T("nnS"), _T("xnS"), NULL } },
    { _T("んT"), { _T("nnT"), _T("xnT"), NULL } },
    { _T("んU"), { _T("nnU"), _T("xnU"), NULL } },
    { _T("んV"), { _T("nnV"), _T("xnV"), NULL } },
    { _T("んW"), { _T("nnW"), _T("xnW"), NULL } },
    { _T("んX"), { _T("nnX"), _T("xnX"), NULL } },
    { _T("んY"), { _T("nnY"), _T("xnY"), NULL } },
    { _T("んZ"), { _T("nnZ"), _T("xnZ"), NULL } }
};

const int g_RomanDictCount = sizeof(g_RomanDict) / sizeof(g_RomanDict[0]);

#endif